### ISSUE TITLE
When calling "getInternetCredentials" with a server param which does not exist throws error

### ISSUE THREAD

**Issue by vairabagni** [oblador/react-native-keychain#1]
In this case it does not even come to catch block of JS, because it stops at native side itself.

Line No 53-54 on RNKeychainManager.m
found = (__bridge NSDictionary*)(foundCF);
  if (!found) return callback(@[[NSNull null]]);

Also if I add following line on top of these it throws some kind of JSON conversion error and stops their:
if (osStatus != 0) {
    NSError *error = [NSError errorWithDomain:NSOSStatusErrorDomain code:osStatus userInfo:nil];
    callback(@[error]);
  }

Any idea?

**Comment by oblador** [comment]
Thanks for your bug report! This was a problem only occurring on device which is now fixed. The JSON conversion is also fixed in a separate commit and this all made it into 0.1.1.
