### ISSUE TITLE
Functionality similar to applicationUUID?

### ISSUE THREAD

**Issue by sjmueller** [oblador/react-native-keychain#10]
MCSMKeychainItem has a very useful feature called [applicationUUID](https://github.com/ObjColumnist/MCSMKeychainItem#mcsmapplicationuuidkeychainitem), which essentially emulates the now-deprecated UIDevice.uniqueIdentifier property.  Is there plans to add the same kind of functionality to react-native-keychain?

**Comment by LeBlaaanc** [comment]
@sjmueller thanks for posting, did you end up implementing `applicationUUID`? 

@oblador I'm not terribly familiar with how this works, could we just store a UUID generated with js into generatePassword in the meantime?

**Comment by oblador** [comment]
I'm not sure that functionality actually makes sense to be in this library, what's your use case?

There's also already another package that does something similar: https://github.com/lazywei/react-native-device-uuid

**Comment by LeBlaaanc** [comment]
It's a way to store a UUID which persists app reinstall. IDFV (which is what the module you suggested provides) will not persist unless two apps from the same vendor are installed.

**Comment by oblador** [comment]
Ah, I'm using an external (ObjC) library currently. The question still persists, should this be a separate module or part of this one?

**Comment by LeBlaaanc** [comment]
I think it could be included with this considering it uses the keychain, this author includes three keychain item types (password, internet password, and applicationuuid) https://github.com/ObjColumnist/MCSMKeychainItem#mcsmapplicationuuidkeychainitem.

That said it might just be for convenience and maybe to use iOS native CFUUID. I honestly don't even know if that method does anything fundamentally different than the `generatePassword()` with a js generated UUID would though.

**Comment by LeBlaaanc** [comment]
Looking closer it does seem this module just uses `setGenericPassword()` storing a generated UUID as the "password" with the BundleID of the app as the username. I'm no ObjC expert does that look what's going on here?
[https://github.com/ObjColumnist/MCSMKeychainItem/blob/master/MCSMKeychainItem.m#L794](url)

**Comment by oblador** [comment]
Closing this as wontfix. There are other libs supporting this already such as [react-native-device-info](https://github.com/rebeccahughes/react-native-device-info).
