### ISSUE TITLE
Use react-native-keychain with create-react-native-app

### ISSUE THREAD

**Issue by Florensvb** [oblador/react-native-keychain#101]
Hey community,

I am trying to make use of this framework while using the `create-react-native-app` (Expo) module. 

I get the following error when trying to call a method on the Keychain:

`undefined is not an object (evaluating 'RNKeychainManager.setGenericPasswordForOptions')`
`node_modules/react-native-keychain/index.js:81:27 in setGenericPassword`
`...`

I have already found the other posted issues about the same error and came to the believe that it is an issue with linking the framework, but unfortunately the command `react-native link` is not available when using `create-react-native-app`. I have also tried to reset the cache, reset the simulator, re-install all node_modules, but without any success.

I import the Keychain like this:
`import * as Keychain from 'react-native-keychain';`

And I am trying to use it like so:
`Keychain.setGenericPassword(this.state.email, this.state.password)
	.then(() => {
	   console.log('Credentials saved successfully!');
	})
	.catch(() => {
	    console.log('Credentials could not be saved!');
});`

Do you have any ideas how to make it work?

Best,

Florens

**Comment by sonnyp** [comment]
You need to eject your app before you can use native modules.

https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md

**Comment by Florensvb** [comment]
Thank you @sonnyp !

I thought I'd have to eject, but I am trying to avoid it, so thanks a lot for the securestore suggestion- thats what I needed.
