### ISSUE TITLE
Removing stored passwords after moving away from react-native-keychain

### ISSUE THREAD

**Issue by yongzhez** [oblador/react-native-keychain#103]
As is recommended by the READme, I have moved away from storing user credentials and now are using tokens for authentication. The question I have now is how to get rid of saved passwords that are left on user devices after this update. What is the recommend approach to solve this?

**Comment by MacKentoch** [comment]
You are right following the good practices.
You'd better reset existing user credential in the next release.
Example:
- if stored with `setGenericPassword ` just use `resetGenericPassword `

*Note: For other users who don't update you cannot do anything obviously.*

**Comment by oblador** [comment]
@MacKentoch is right, closing this issue for now 👍
