### ISSUE TITLE
Crash on Android 4.4

### ISSUE THREAD

**Issue by rajivshah3** [oblador/react-native-keychain#105]
Hi,
I'm experiencing a crash on Android 4.4 (Samsung Galaxy Mini S4). When I store an item in the keychain, the app crashes and provides this crash log: https://pastebin.com/9R9zwt5v. In other environments, the app works normally. Is this a device-specific issue?

**Comment by cvarley100** [comment]
Also experiencing this crash. 

@oblador It seems the facebook conceal function is causing the crash. Do you have any idea what the problem might be?

**Comment by vonovak** [comment]
closing as outdated, please open a new issue if the problem persists, and please include a repro.
