### ISSUE TITLE
Reset do not delete the record.

### ISSUE THREAD

**Issue by malashkevich** [oblador/react-native-keychain#106]
I'm using v2.0.0
Tested on iOS only.

I have this code:
```
  return Keychain.resetGenericPassword('first_run')
    .then(() => {
      return Keychain.getGenericPassword('first_run');
    })
    .then(value => {
      debugger;
    })
    .catch(() => {
      debugger;
    });
```

Keychain already has value `first_run`. And I want just to clear it but seem like it's not working.
I just put this code to detect what's going wrong.
And as result, I still get `debugger` inside `then` section instead of `catch`.
Could you pls help me with this?

**Comment by vonovak** [comment]
in `then`, what is the value of `value`?

**Comment by malashkevich** [comment]
@vonovak `false`. This is value that I set there before

**Comment by oblador** [comment]
False is the value returned if there's no data stored. Keychain only accepts strings, so I'd suggest to refactor it to use some string constant instead.

**Comment by oblador** [comment]
I'm surprised it even accepted the boolean.

**Comment by malashkevich** [comment]
Yes, you are right, it's `'false'`. Sorry for my mistake

**Comment by malashkevich** [comment]
@oblador, why you closed this? :)
I still have this issue.

**Comment by vonovak** [comment]
@malashkevich please state **exactly** what you're saving into the keychain, what the expected behavior is and what the actual outcome it. It's currently not clear what the issue is.

**Comment by malashkevich** [comment]
Hmmm, ok.
I’m trying to clear value in keychain. And after clearing I’m trying to get already cleared value.
I expect that I shouldn’t get the value and block catch will be executed.
But actually executed block then with last saved value.
It seems that reset method do not work as expected.

**Comment by vonovak** [comment]
@malashkevich please be more specific. What value are you trying to save to the keychain?

If a value is not in keychain, the `Keychain.resetGenericPassword` will **resolve** to `false`. That means it won't reject, which means it will never get to the `catch` part.

**Comment by malashkevich** [comment]
@vonovak, I just wanted to comment all my code from the original issue but decided to test a bit more. And seems like `Keychain.getGenericPassword` will resolve to false in case if there is no such record instead of throwing an error. I don't find this in docs - so I'm not sure about it.
I thought it should throw an error if there is no such value. Hmm, probably there were changes in lib - I recently updated my app.

Anyway thanks for your time, @vonovak @oblador!

**Comment by vonovak** [comment]
I updated the readme to make the usage clearer. Thanks for reporting.

**Comment by oblador** [comment]
@malashkevich There was an inconsistency in behavior between iOS and Android for a while, but it was fixed quite long ago, maybe you recently upgraded?

**Comment by malashkevich** [comment]
@oblador, Yeah, this issue raised after bulk update of all libs on a project. 
Thanks, @vonovak for updating docs. I think this would be helpful to other developers.

**Comment by BenRGleason** [comment]
@malashkevich your correct the record still accessible, I tried it when I access a shared keychain in our ios extension app.

**Comment by mechazod** [comment]
@malashkevich your correct the record still accessible, I tried it when I access a shared keychain in our ios extension app.
