### ISSUE TITLE
Keychain and Flux/Redux

### ISSUE THREAD

**Issue by alvaromb** [oblador/react-native-keychain#11]
I'm curious Joel, have you used the ``Keychain`` with some kind of Flux implementation?

If so, let's say you get an API key in your login response. Where exactly do you save your keychain items? I think it should live in the reducer, but I'm not completely sure.

**Comment by oblador** [comment]
Hi, I don't use Redux so can't speak for how it would work there. With API key, I'm assuming a token? If so then I'd put that in some kind of session store and then the credentials used to generate the token into the keychain. A token isn't as sensitive as the credentials and a store has the advantage of being synchronous, but I guess it's not wrong to store that too in the keychain. 

I personally also wrap `fetch` to inject the token and request a new one if it's expired. 

Don't know if that actually answered your question :-)

**Comment by alvaromb** [comment]
Yes! thanks @oblador.

I'm using ``async/await`` to retrieve the keychain data in my ``fetch`` wrapper, but I think I'll move to save the token in another place and just save the user credentials in the keychain.
