### ISSUE TITLE
Touch ID prompt not showing when using accessControl on emulator

### ISSUE THREAD

**Issue by crisppY** [oblador/react-native-keychain#111]
```
async componentDidMount() {

    await Keychain.resetGenericPassword();
    
    
      await Keychain.setGenericPassword('username', 'secret', {
        accessControl: Keychain.ACCESS_CONTROL.BIOMETRY_ANY_OR_DEVICE_PASSCODE
      });

    var privateKey = await Keychain.getGenericPassword();

    console.log(privateKey)


  }
```

The app is able to set and grab a set of credentials without any biometric or passcode authentication. What am I doing wrong here?

**Comment by oblador** [comment]
This is a limitation of the simulator, try it on a real device instead :-)

**Comment by crisppY** [comment]
Hmm, unfortunate. Closing.

**Comment by jpmonette** [comment]
You can also make sure on your simulator that you are Enrolled for Touch ID so it prompts you for fingerprint - worked for me.

![capture d ecran 2018-04-10 a 14 50 24](https://user-images.githubusercontent.com/1114325/38560865-8cba7346-3cce-11e8-8074-c7b2b4466ced.png)

**Comment by anagar23** [comment]
@oblador , I am testing it on Android device but still not getting Fingerprint pop up. Does this functionality only works for iOS ? 

If so, can you suggest me how can I validate it on Android ?

Thanks.
