### ISSUE TITLE
Keychain validity period | expiry

### ISSUE THREAD

**Issue by MwirabuaTim** [oblador/react-native-keychain#119]
I am using this package to save JWT tokens instead of actual passwords. Is there a validity period for what you save to the Keychain? Or an API to set that for either IOS or Android...
Otherwise I guess I will have to manually delete the tokens after a given period and refresh them...

**Comment by TechyTimo** [comment]
So this means the credentials are stored on the keychain **indefinitely**? No external events (from OS, other apps) can clear it except from your app code?

**Comment by oblador** [comment]
You can clear it by uninstalling the app, but even that will not clear it directly.

**Comment by vonovak** [comment]
please see answer from eskimo in https://forums.developer.apple.com/thread/36442
