### ISSUE TITLE
keychain + sharedpreferences support

### ISSUE THREAD

**Issue by geirman** [oblador/react-native-keychain#12]
wondering  if you plan to also include [SharedPreferences](http://developer.android.com/reference/android/content/SharedPreferences.html) support for Android. A single component that abstracts both would be awesome.

**Comment by oblador** [comment]
It's definitely planned, but no ETA right now. A PR would be highly appreciated!

**Comment by chrisvariety** [comment]
I think Keystore would be more appropriate? http://developer.android.com/training/articles/keystore.html

SharedPreferences isn't encrypted.

**Comment by corymsmith** [comment]
Was having a look at this the other day, may do an implementation with https://facebook.github.io/conceal/ and ship a PR over.

**Comment by geirman** [comment]
That looks pretty awesome, @corymsmith

**Comment by corymsmith** [comment]
@geirman I'll probably start digging into this today :)

**Comment by oblador** [comment]
@corymsmith :clap: :bow:

**Comment by corymsmith** [comment]
Ran into some conflicts with React Native so had to update Conceal to fix it. 

https://github.com/facebook/conceal/pull/105

Made some great progress today! It looks like there are some issues with Conceal on recent Android versions that are in progress so will have to see how that progresses.!

**Comment by liorsaar1** [comment]
@corymsmith  are you creating an android version for this ?  would like to collaborate - liorsaar1@gmail.com

**Comment by corymsmith** [comment]
@liorsaar1 Yes, I have some updates in the android-support branch of my fork. I was having some issues unencrypting and still working through the best approach for Android. I broke my arm so can't do much until thats all sorted unfortunately

**Comment by oblador** [comment]
@corymsmith: :clap: so excited about this! Get well :mask:

**Comment by paulondc** [comment]
Any updates about the android support ? I'm very excited about it :)

**Comment by corymsmith** [comment]
@paulondc I've been super busy as of late with a few other open source projects and my new consulting company so haven't looked at this in a it but it was super close when I last left off. I'll be needing this in a few apps in the near future so hoping to pick it back up and wrap a release in the next few weeks or less

**Comment by paulondc** [comment]
Thanks @corymsmith for all effort you are putting on this :clap:

I wonder if we could help you somehow, since this is going to introduce the initial support for android, I think we could have a special branch under this repository for this feature, so everybody interested on this could try it, watch the progress, create pull request, etc..

What do you guys think about it ?

**Comment by corymsmith** [comment]
@paolondc The branch is here: 

https://github.com/corymsmith/react-native-keychain/tree/android-support

**Comment by vonovak** [comment]
nice work! @paulondc when can we expect the android support in npm? Thanks!

**Comment by oblador** [comment]
Finally 0.3.0 with android support is on npm. Thanks to everyone involved making this happen!

**Comment by rops** [comment]
Hi folks, I was just wondering if there was any particular (security or performance) reason why Android's KeyStore wasn't used

**Comment by vonovak** [comment]
Hello,
Someone started the android implementation a while ago and used the
Facebook conceal in it. It was, however, incomplete and wasn't merged. I
picked it up and finished it. Not sure what the initial reasons were but
IMHO there is no big difference. With conceal you get support in <= 4.3 and
perhaps greater flexibility in what you can save.
