### ISSUE TITLE
Missing "accessible" in types

### ISSUE THREAD

**Issue by jpmonette** [oblador/react-native-keychain#121]
This should include `accessible` for types:

```ts
type Options = {
  accessControl?: SecAccessControl,
  accessGroup?: string,
  accessible?: SecAccessible,
  authenticationPrompt?: string,
  authenticationType?: LAPolicy,
  service?: string,
};
```

https://github.com/oblador/react-native-keychain/blob/ee959ba42eb0e6695c98bf135e67f98756ef05b8/typings/react-native-keychain.d.ts#L14

**Comment by vonovak** [comment]
this should be now fixed; please open a PR if its' not
