### ISSUE TITLE
getGenericPassword sometimes doesn't return the password even if I didn't call resetGenericPassword

### ISSUE THREAD

**Issue by buttifabio** [oblador/react-native-keychain#124]
I use `saveGenericPassword` to store auth credentials after login process.
At app start i call `getGenericPassword`: if i get result i show the main authenticated screen, otherwise i show login screen.
The main authenticated screen has a logout button that calls `resetGenericPassword` and go back to login screen.

Most of the times it works but after some app kills and reopen the app randomly doesn't get credentials from `getGenericPassword` showing login page.
I need to keep my users logged in and this "random" behaviour is a problem.
What could i do to resolve this problem?

Happened on the following setup:
- react-native: 0.51.0
- react-native-keychain: 2.0.0

Tested mostly on iOS

Code in index.js:
```
require('react-native-keychain').getGenericPassword().then(credentials => {
  if (credentials) {
    // Show authenticated screen
  } else {
    // Show login screen
  }
})
```

**Comment by vonovak** [comment]
@buttifabio we will need a minimal reproduction to be able to see what is happening. 

> Tested mostly on iOS

So what platforms are affected? Both ios and android?

**Comment by buttifabio** [comment]
Nevermind... after deeper tests I found it was my fault.
I was calling a `resetGenericPassword` if the main authenticated screen couldn't retrieve data from cache (don't ask me why... i don't know 😰)... so the issue happened randomly because it depended from what was loaded first between the screen component and cache data.

Anyway, thank you for your help.
