### ISSUE TITLE
Android - Multiple Credentials

### ISSUE THREAD

**Issue by ben-snaize** [oblador/react-native-keychain#127]
Hi,

I've got this working perfectly on iOS, with the correct dialogue being prompted when using`requestSharedWebCredentials`. However, when using `getInternetCredentials` on Android, only  the latest credential is returned (having been set by `setInternetCredentials`). The native Android dialogue is not prompted so a credential cannot be chosen.

Is there a way to implement this?

Thanks

**Comment by kulkarniankita** [comment]
Did you figure out android yet? @ben-snaize
