### ISSUE TITLE
What is the difference between BIOMETRY_ANY and BIOMETRY_CURRENT_SET?

### ISSUE THREAD

**Issue by somoso** [oblador/react-native-keychain#129]
So I'm looking at the Keychain.ACCESS_CONTROL enum values as documented and I see these two entries:

* BIOMETRY_ANY
* BIOMETRY_CURRENT_SET

And I'm pretty confused as I don't seem to see in iOS a concept of a "currently enrolled finger" vs all of the fingers the user has enrolled on their device. As the title says, what is the difference between the two?

**Comment by oblador** [comment]
Basically if you were to add a new enrolled fingerprint it won't be able to unlock with the setting `BIOMETRY_CURRENT_SET` whereas it would if you were using `BIOMETRY_ANY`

**Comment by jneuendorf** [comment]
@oblador The `ACCESS_CONTROL` also confused me. Maybe your explanation should become part of the docs/readme?

**Comment by imdaniele** [comment]
Using Android, I set my password with

```
Keychain.setGenericPassword(username, password, {
      service: SERVICE_NAME,
      accessible: Keychain.ACCESSIBLE.WHEN_UNLOCKED_THIS_DEVICE_ONLY,
      accessControl: Keychain.ACCESS_CONTROL.BIOMETRY_CURRENT_SET,
    })
```

and I get the password with

Keychain.getGenericPassword({
      service: SERVICE_NAME,
    })

but when I try to get the same password after removing all current fingerprints from the device and enrolling a new one, it still gives me the correct result, no errors or warnings.

How can I get an error if the enrolled fingerprints has changed?

**Comment by wadeking98** [comment]
@imdaniele I think that `BIOMETRY_CURRENT_SET` isn't supported by android. I've ran into the same issue. Read the note here: https://github.com/oblador/react-native-keychain#keychainaccess_control-enum
