### ISSUE TITLE
Example app not working

### ISSUE THREAD

**Issue by gre** [oblador/react-native-keychain#130]
if you `yarn` and then deploy the KeychainExample app, it crashes.

it pulls the wrong version of the library, and it breaks with `undefined is not an object (evaluating 'Keychain.ACCESS_CONTROL.DEVICE_PASSCODE')`

To fix it locally, I changed the dependency to `"react-native-keychain": "file:.."`. I'm not sure if you want to do this in the example app or you want to release a new version and properly set the correct version in package.json

**Comment by 0xc0d3r** [comment]
I'm also getting above issue.

```
"dependencies": {
    "react": "16.2.0",
    "react-native": "0.53.3",
    "react-native-keychain": "^2.0.0"
  },
  "devDependencies": {
    "babel-jest": "22.4.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.2",
    "react-test-renderer": "16.2.0"
  },
  "jest": {
    "preset": "react-native"
  }
```

**Comment by 0xc0d3r** [comment]
Did you figure it out why the example is not working?

**Comment by oblador** [comment]
Hi, yeah the example package.json was referencing an older version so I just bumped it 😊 Try now!
