### ISSUE TITLE
How to call synchronously?

### ISSUE THREAD

**Issue by devxpy** [oblador/react-native-keychain#137]
This would be useful, for example:

I have to check whether user is loggin in or not, and show them  a different landing page, depending on that.

So i need the `getGenericPassword()` operation to be synchronous, because the landing page depends on it.

**Comment by LinusU** [comment]
It's not possible to communicate synchronously between the JS Thread and the Native Thread, so this will not be possible to support unless something changes in React Native.

That being said, could you just render an empty `<View />` until you get the response?

**Comment by vonovak** [comment]
@devxpy yes, due to the async nature of RN, this is currently not possible. You need to have a state that will contain whatever is being loaded from keychain. While it is not loaded, you just need to render a splash screen or some placeholder view.
