### ISSUE TITLE
Getting Lint error for Android release build

### ISSUE THREAD

**Issue by sanjaykumarbal** [oblador/react-native-keychain#138]
../../../../node_modules/react-native-keychain/android/src/main/java/com/oblador/keychain/DeviceAvailability.java:13: Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with checkPermission) or explicitly handle a potential SecurityException
 10        if (android.os.Build.VERSION.SDK_INT >= 23) {
 11            FingerprintManager fingerprintManager =
 12                (FingerprintManager) context.getSystemService(Context.FINGERPRINT_SERVICE);
 13            return fingerprintManager.isHardwareDetected() &&                                       
 14                fingerprintManager.hasEnrolledFingerprints();
 15        }
 16        return false;
../../../../node_modules/react-native-keychain/android/src/main/java/com/oblador/keychain/DeviceAvailability.java:14: Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with checkPermission) or explicitly handle a potential SecurityException
 11             FingerprintManager fingerprintManager =
 12                 (FingerprintManager) context.getSystemService(Context.FINGERPRINT_SERVICE);
 13             return fingerprintManager.isHardwareDetected() &&
 14                 fingerprintManager.hasEnrolledFingerprints();                                       
 15         }
 16         return false;
 17     }
This check scans through your code and libraries and looks at the APIs being used, and checks this against the set of permissions required to access those APIs. If the code using those APIs is called at runtime, then the program will crash.

Furthermore, for permissions that are revocable (with targetSdkVersion 23), client code must also be prepared to handle the calls throwing an exception if the user rejects the request for permission at runtime.

**Comment by vonovak** [comment]
closing as outdated, please open a new issue if the problem persists, and please include a repro.
