### ISSUE TITLE
TypeError: Cannot read property 'setGenericPasswordForOptions' of undefined

### ISSUE THREAD

**Issue by AGASampath** [oblador/react-native-keychain#147]

**Comment by LinusU** [comment]
Probably the same problem as #144?

**Comment by AGASampath** [comment]
no

**Comment by LinusU** [comment]
Why do you think that? 🤔

**Comment by vonovak** [comment]
@AGASampath this indeed seems to be a duplicate of #144 - please make sure the module is linked correctly
