### ISSUE TITLE
Keychain getting wiped when app updates?

### ISSUE THREAD

**Issue by wstuckmeyer** [oblador/react-native-keychain#152]
For some reason it seems like a select few of users' keychains are getting wiped after they update my app. I'm using this to store JWT tokens and refresh tokens. So for a few people when they update their app it looks like none of the tokens are there causing an empty app. Any ideas what would cause this?

**Comment by Cederman** [comment]
Me and my team experienced the same issue. Our conclusion so far is that it changed when upgrading from iOS 11 to iOS 12 due to keychain access being different.

**Comment by tommynordli** [comment]
I'm experiencing the same issue. I updated react-native and re-created and re-linked the iOS-project (`rm -rf iOS && react-native upgrade && react-native link`, and guessing the latter is the reason keychain is getting wiped after this app update. Anyone know why it happens though?

**Comment by vonovak** [comment]
closing as outdated, please open a new issue if the problem persists, and please include a repro.
