### ISSUE TITLE
iOS crashing upon loading

### ISSUE THREAD

**Issue by eladgel** [oblador/react-native-keychain#154]
Tried running my iOS app with this library, and the app crashes upon loading of this library

VVV Point of crashing VVV
![image](https://user-images.githubusercontent.com/412137/46232355-d20ae080-c323-11e8-96fa-00d10b362673.png)

VVV upper stack of crash VVV
![image](https://user-images.githubusercontent.com/412137/46232532-53fb0980-c324-11e8-9924-aeab6610ce1e.png)

**Comment by vonovak** [comment]
hi, thanks for opening an issue but it's impossible to debug a problem from a screenshot. Please open a new issue with a repro if the problem persists.
