### ISSUE TITLE
is this lib reliable than react-native Asynstorage?

### ISSUE THREAD

**Issue by fuj1w4r4** [oblador/react-native-keychain#159]
Hi there, 

After several firefighting with react native asynstorage issue (promise never resolve and stucking), it frustrates me and impacted my users. 

A lot of users reported in https://github.com/facebook/react-native/issues/18372

So, my question is, does this happen to react-native-keychain?

Thanks and regards,
Fuji

**Comment by Rutheniceye92** [comment]
This might help..
[https://stackoverflow.com/questions/39148714/is-react-natives-async-storage-secure](url)

**Comment by vonovak** [comment]
I think you'd need to run some tests to answer this. Also, async storage is going through its own development, so this will change with time.
