### ISSUE TITLE
Cant get it to work. Cannot read property 'setGenericPasswordForOptions' of undefined

### ISSUE THREAD

**Issue by ibrahimokdadov** [oblador/react-native-keychain#161]
I have read through similar issues and re-building (even with reset cache) does not seem to work. 
Any ideas on where to look? 

I think this looks like [Issue 84](https://github.com/oblador/react-native-keychain/issues/84) but not sure how it was solved. As RNKeychainManager is undefined in index.js of the component react-native-keychain. Here is how I came to that realization: 

RN version is 57
Keychain v: 3

I used the latest react-native-keychain through npm install --save. and double checked on the manual installation all links exist, in the gradle and mainactivity files. 

Here is my example:

```
import * as Keychain from 'react-native-keychain';
class demo extends Component {
 componentWillMount() {

console.log(keychain)
 try {
      Keychain.setGenericPassword(          
         {'key1':'test'} 
      ).then(function(){
        console.log("all clear....set the credentials")
      }).catch(function(error) {
        console.warn('Keychain couldn\'t be set!', error);
      });;
      
      
    } catch (err) {
      console.log("error persisting tokens", err)
    }

}

async load()  {

    try {
      const credentials = await Keychain.getGenericPassword(); 
      if (credentials) {
        console.log("credentials are ", credentials)
        this.props.setTokens(tokens);
        
      } else {
        console.log("could not load credentials", credentials)
      }
    } 
  catch (err) {
      console.log("error getting credentials", err)
    }


  };
```

... rest of the class

when I console.log Keychain on componentWillMount I see all the methods in it. So I am guessing it is not a link problem? 

Here is the output of console.log(keychain): `Keychain {canImplyAuthentication: ƒ, getSupportedBiometryType: ƒ, setInternetCredentials: ƒ, getInternetCredentials: ƒ, resetInternetCredentials: ƒ, …}`

When I call either getGenericPassword...or setGenericPassword I get Cannot read property 'setGenericPasswordForOptions' of undefined

If it is worth noting: when I try to debug index.js of the moduie:
```
export function setGenericPassword(
  username: string,
  password: string,
  serviceOrOptions?: string | Options
): Promise {
  console.log("hello", username, password, serviceOrOptions);
  return RNKeychainManager.setGenericPasswordForOptions(
    getOptionsArgument(serviceOrOptions),
    username,
    password
  );
}
```

the function is actually hit and console.log prints the passed parameters in my case 'test1'. The issue is in the return that follows. What do you recon I am doing wrong?

**Comment by mdere** [comment]
Bump...same issue...

**Comment by mdere** [comment]
@ibrahimokdadov - so I had this same issue for sure until I realized I forgot to link react-native-keychain - now it works.... so dumb question - did you link?

**Comment by ibrahimokdadov** [comment]
@mdere I did actually :D.. Followed the manual process as well...any other ideas?

**Comment by ibrahimokdadov** [comment]
I am not sure if I should close this or not. Tried everything possible but couldn't get it work. However one think that partially worked is when I started debugging through a USB. I was able to see it set but does not persist. It is always empty when reading.

After all of this I opted for another approach using the default Async module.

**Comment by mdere** [comment]
Sorry man - I can't think of any other issues.....the linking was my resolution

**Comment by Zaporozhec7** [comment]
Linking did not help in my case. I have checked all required files and there was added all required code

**Comment by Zaporozhec7** [comment]
I have fixed it! Seems problem was in using with **react-native-navigation** library. Here is how it was fixed - https://github.com/oblador/react-native-vector-icons/issues/591#issuecomment-445037756

**Comment by hubyrod** [comment]
Hi, 
I'm having the same problem on iOS. Eventhough i tried (and failed) the patch you proposed in the Android MainApplication.java file, I still puzzled by the iOS failure. 
Would you have any advice to get started on the debugging of it?

**Comment by tirsoh** [comment]
I was able to get past this error when I followed the manual link instructions. The react-native link said it worked but it must not have.

**Comment by sergioutama** [comment]
@tirsoh @ibrahimokdadov just curious wether you guys already have cocoapods set before using this library. If cocoapods already installed, there is additional step that need to be done which is to run `pod install`

**Comment by ibrahimokdadov** [comment]
@sergioutama I did not have that tbh...

**Comment by traviswimer** [comment]
@sergioutama `pod install` fixed it for me.

I've run into this before with other libraries, but always forget. I wonder why `react-native link` doesn't automatically run `pod install` when necessary.

**Comment by vonovak** [comment]
hi! There is a problem with how the project is linked. Please open a new issue with a minimal runnable repro (https://stackoverflow.com/help/reprex) so we can fix it.
