### ISSUE TITLE
Got error TypeError: undefined is not an object (evaluating 'RNKeychainManager.setGenericPasswordForService'

### ISSUE THREAD

**Issue by johnnynanjiang** [oblador/react-native-keychain#17]
Got the error when calling Keychain.setGenericPassword()

**Comment by oblador** [comment]
You most likely didn't integrate the objc parts into your project, check the readme.

**Comment by latish** [comment]
@johnnynanjiang did you ever figure this out? I am running into the same issue, and have double checked that the objc parts are integrated correctly (used rnpm to begin with).

**Comment by Mjuk-Biltvatt** [comment]
@latish Did you ever figure this out?

**Comment by latish** [comment]
@Mjuk-Biltvatt I think I was getting the error when I was passing in the optional service argument. I only pass 2 arguments now, and seems to work.

**Comment by Mjuk-Biltvatt** [comment]
@latish I figured out my issue right after I commented. It seems that I simply missed the step "react-native link". This solved it for me. Thank you though!

**Comment by harikrishnanp** [comment]
Issue command `react-native link` and re-run with `react-native run-android` or `react-native run-ios`
