### ISSUE TITLE
NSFaceIDUsageDescription

### ISSUE THREAD

**Issue by rossgeesman** [oblador/react-native-keychain#172]
I'm attempting to integrate this library into an iOS app I'm working on. I was unable to get the simulator to prompt me for a password or biometric auth. `Keychain.getGenericPassword()` was just retrieving the stored data so instead I tried simulating on my device (iPhone X) instead. The app built and ran fine but when code calling executed`Keychain.getGenericPassword()` it crashed with the following message:

`This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSFaceIDUsageDescription key with a string value explaining to the user how the app uses this data.`

Is Info.plist something I should be manually updating or is this library supposed to take care of it for me? 

For reference my code for getting and setting the keychain data looks like this:

```
export const storeIdentity = async (privateKey, account) => {
  await Keychain.resetGenericPassword()
  await Keychain.setGenericPassword(account, privateKey, {accessControl: Keychain.ACCESS_CONTROL.BIOMETRY_ANY});
}
```
```
export const retrieveIdentity = async () => {
  try {
    const identity = await Keychain.getGenericPassword();
    if (identity) {
      console.log('Credentials successfully loaded for user ' + identity.username, identity.password);
    } else {
      console.log('No credentials stored')
    }
  } catch (error) {
    console.log('Keychain couldn\'t be accessed!', error);
  }
}
```

**Comment by vonovak** [comment]
hi! Thanks for reporting.

> Is Info.plist something I should be manually updating or is this library supposed to take care of it for me?

this is a developer responsibility. Thanks.
