### ISSUE TITLE
64 bit native library

### ISSUE THREAD

**Issue by malonguwa** [oblador/react-native-keychain#180]
Google Play will start to ONLY accept 64-bit version android App if there is any native code in the project after Aug 2019:
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

Does this react-native-keychain lib is in 32-bit? or 64-bit? I am still new to the android, the react native 0.58 will included the support of 64-bit version of react native app, does this react-native-keychain will be able to provide 64-bit version, so we can able to keep using this lib after 2019 Aug -  Google Play's new policy?

**Comment by vonovak** [comment]
hi! I don't think this should be an issue, but it does turn out to be a problem, it will be fixed.
