### ISSUE TITLE
Geting only last username/password combination iOS

### ISSUE THREAD

**Issue by osmancikjan** [oblador/react-native-keychain#185]
Hello, I am using your react-native module to store credentials in app. So I need to store multiple credentials for multiple users (unique username/stringified JSON object). I am using setGenericPassword(username, string representation of JSON object) method to store credentials. The problem is, when I add more than one user's credentials. I am using getGenericPassword() method and always obtaining only the last user's credentials. It happens in iOS version of app.

**Comment by keyneslim** [comment]
There are few way you can achieve that.
1. provide different service name when setGenericPassword
2. store a map/array of username and password

**Comment by vonovak** [comment]
hi! closing as the question was answered

**Comment by emclab** [comment]
> 
> 
> There are few way you can achieve that.
> 
>     1. provide different service name when setGenericPassword
> 
>     2. store a map/array of username and password

Can you provide an example for the 2 options you provide? one or two line of code would help greatly. Thanks.
