### ISSUE TITLE
Migrate to androidx

### ISSUE THREAD

**Issue by loic-lopez** [oblador/react-native-keychain#187]
Hello,

Do you have plans to migrate on androidx?

Thanks for reply. 👍

**Comment by mikaoelitiana** [comment]
That would be really helpful as I am currently having issues on a project using react-native-keychain that I am migrating to androidx

**Comment by Bardiamist** [comment]
Need migrate when react-native 0.60.0 will relised [AndroidX Migration Plan](https://github.com/react-native-community/discussions-and-proposals/issues/129)

**Comment by developersHomefriend** [comment]
iam having issue also when migrating on androidX, any help

**Comment by Xesme** [comment]
Has anyone made progress on this or found a fix for their projects on AndroidX? I am facing the same issue. Thanks!

**Comment by vonovak** [comment]
a PR for androidX is welcome

**Comment by hellogerard** [comment]
PR: #226

**Comment by tim-cdl** [comment]
Is there a plan to merge this anytime soon?

Thanks :)

**Comment by loic-lopez** [comment]
@tim-cdl but as for now you can use : [mikehardy/jetifier](https://github.com/mikehardy/jetifier)

**Comment by vonovak** [comment]
this is now released in v4
