### ISSUE TITLE
Are we supposed to encode passwords before saving them on disk, or does this library do that for us?

### ISSUE THREAD

**Issue by SudoPlz** [oblador/react-native-keychain#190]
Hey there,

I'll be using this library to save credentials on the disk with `setGenericPassword`.
Is it my duty to encode those credentials with something like base64 before storing, or does that library do that for us?

Is it safe to not encode at all i.e save the password in plan text? (I mean at least for iOS we're saving it on iOS keychain right? What about Android?)

Thank you

**Comment by vonovak** [comment]
hi!
> Is it my duty to encode those credentials with something like base64

no, you don't need to do that

> Is it safe to not encode at all

encoding does not add any security whatsoever, so it does not matter whether or not you encode
