### ISSUE TITLE
method encrypt in class Cipher Storage KeystorE cannot be applied to given types; return encrypt(service, username, password);'

### ISSUE THREAD

**Issue by coderscode2** [oblador/react-native-keychain#191]
Started getting this error on android(DeviceAvailability.java) with latest update that happened like 3 hours ago. 

I had to go back to use earlier version  3.0.0 for my app to work
**ERROR**
node_modules/react-native-keychain/android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java:111: error: method encrypt in class CipherStorageKeystoreAESCBC cannot be applied to given types;
                    return encrypt(service, username, password);
                           ^
  required: String,String,String,SecurityLevel
  found: String,String,String
  reason: actual and formal argument lists differ in length

**Comment by ralesiupgrade** [comment]
i was just about to report this. thanks

**Comment by ralesiupgrade** [comment]
I think it might be related to https://github.com/oblador/react-native-keychain/commit/ee9cf16187367b1403df81adc1541fe06a7a4f52#diff-ff40e52a001d72ceed560efa9e57466cR101

**Comment by ralesiupgrade** [comment]
looks like there on it https://github.com/oblador/react-native-keychain/commit/b2e54cced98c09fb43a3f6d9d3efd9e3aff4b779

**Comment by ralesiupgrade** [comment]
trying 3.1.1 now

**Comment by oblador** [comment]
Hey, just released a fix for this: https://github.com/oblador/react-native-keychain/releases/tag/v3.1.1

**Comment by ralesiupgrade** [comment]
ok looks like it worked thanks!

**Comment by vonovak** [comment]
fixed
