### ISSUE TITLE
Question Android: how should the library work on Android?

### ISSUE THREAD

**Issue by MarcoLude** [oblador/react-native-keychain#194]
Sorry to bother you with this simple question:
How should be the workflow on Android devices? On iOS, if I save the credentials with AccessControl and AuthenticationType arguments, when I try to access them the iOS triggers touchID or passcode.. But If I try to do the same in android nothing happens, I get the credentials without passcode or fingerprint being prompt. So what should I do to achieve the same iOS result on android?

EDIT:
Waiting for https://github.com/oblador/react-native-keychain/pull/195

**Comment by vonovak** [comment]
closing since this issue is about having fingerprint supported on android

**Comment by v4g0** [comment]
I have the same issue with a device with support for fingerprint

**Comment by Thembelani** [comment]
Apparently the feature hasn't been fully implemented for android
