### ISSUE TITLE
Error when loading credentials

### ISSUE THREAD

**Issue by adamkrell** [oblador/react-native-keychain#2]
When using the component I'm getting an error when attempting to load credentials: `"line":51735,"column":56`. Saving the credentials seems to work fine.

Also, the example project won't compile: `.../react-native-keychain/RNKeychainManager/RNKeychainManager.h:9:9: 'RCTBridgeModule.h' file not found`

Am I missing something? Do I need to set headers search path on the example project?

**Comment by chirag04** [comment]
did you npm install inside the examples folder?

**Comment by adamkrell** [comment]
@chirag04 That's it. I totally forgot that. Now I need to see why I can't get loading credentials to work.

**Comment by chirag04** [comment]
@adamkrell  Make sure you are not resetting anything before you load. reset will clear the keychain data as well.

**Comment by adamkrell** [comment]
@chirag04 It looks like I wasn't binding my ES6 method to this. Thanks for helping.
