### ISSUE TITLE
Error : TypeError: Keychain.getSecurityLevel is not a function

### ISSUE THREAD

**Issue by janet-rivas** [oblador/react-native-keychain#200]
Running on Android I cannot get getSecurityLevel  even when I open react-native-keychain.d.ts the function is not there, and the version that I'm using is react-native-keychain": "^3.0.0"  even KeyChainExample does not work

**Comment by mandrigin** [comment]
It was introduced in 3.1.0, what happens if you upgrade?

**Comment by janet-rivas** [comment]
Thank you for your quick response 
"react-native-keychain": "^3.1.0" this is after upgrade react-native-keychain , I'm not seeing  getSecurityLevel function :(  

`declare module 'react-native-keychain' {

    export interface UserCredentials {
        username: string;
        password: string;
    }

    export interface SharedWebCredentials {
        server: string;
        username: string;
        password: string;
    }

    export enum ACCESSIBLE   {
        WHEN_UNLOCKED = "AccessibleWhenUnlocked",
        AFTER_FIRST_UNLOCK = "AccessibleAfterFirstUnlock",
        ALWAYS = "AccessibleAlways",
        WHEN_PASSCODE_SET_THIS_DEVICE_ONLY = "AccessibleWhenPasscodeSetThisDeviceOnly",
        WHEN_UNLOCKED_THIS_DEVICE_ONLY = "AccessibleWhenUnlockedThisDeviceOnly",
        AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY = "AccessibleAfterFirstUnlockThisDeviceOnly",
        ALWAYS_THIS_DEVICE_ONLY = "AccessibleAlwaysThisDeviceOnly"
    }

    export enum ACCESS_CONTROL {
        USER_PRESENCE = "UserPresence",
        BIOMETRY_ANY = "BiometryAny",
        BIOMETRY_CURRENT_SET = "BiometryCurrentSet",
        DEVICE_PASSCODE = "DevicePasscode",
        APPLICATION_PASSWORD = "ApplicationPassword",
        BIOMETRY_ANY_OR_DEVICE_PASSCODE = "BiometryAnyOrDevicePasscode",
        BIOMETRY_CURRENT_SET_OR_DEVICE_PASSCODE = "BiometryCurrentSetOrDevicePasscode"
    }

    export enum LAPolicy {
        DEVICE_PASSCODE_OR_BIOMETRICS = "AuthenticationWithBiometricsDevicePasscode",
        BIOMETRICS = "AuthenticationWithBiometrics"
    }

    export interface Options {
        accessControl?: ACCESS_CONTROL;
        accessGroup?: string;
        accessible?: ACCESSIBLE;
        authenticationPrompt?: string;
        authenticationType?: LAPolicy;
        service?: string;
    }

    function canImplyAuthentication(
        options?: Options
    ): Promise<boolean>;

    function getSupportedBiometryType(
    ): Promise<string>;

    function setInternetCredentials(
        server: string,
        username: string,
        password: string,
        options?: Options
    ): Promise<void>;

    function getInternetCredentials(
        server: string
    ): Promise<UserCredentials>;

    function hasInternetCredentials(
        server: string
    ): Promise<boolean>;

    function resetInternetCredentials(
        server: string
    ): Promise<void>;

    function setGenericPassword(
        username: string,
        password: string,
        options?: Options
    ): Promise<boolean>;

    function getGenericPassword(
        options?: Options
    ): Promise<boolean | {service: string, username: string, password: string}>;

    function resetGenericPassword(
        options?: Options
    ): Promise<boolean>

    function requestSharedWebCredentials (
    ): Promise<SharedWebCredentials>;

    function setSharedWebCredentials(
        server: string,
        username: string,
        password: string
    ): Promise<void>;

}
`

**Comment by mandrigin** [comment]
yeah, it is definitely an old version, which package manager are you using? npm, yarn or something else?

**Comment by janet-rivas** [comment]
npm

**Comment by mandrigin** [comment]
no, but try running `npm update react-native-keychain@3.1.1` and see if the files in your `node_modules` change

**Comment by vonovak** [comment]
I think the complaint is about getSecurityLevel not being present in the ts typing. Could you please provide a PR that fixes this?

**Comment by janet-rivas** [comment]
I did update it uninstalling and installing again however I'm not able to run 3.1.1 
![image](https://user-images.githubusercontent.com/28309400/53138484-6cc6be80-3554-11e9-9f03-2cf012414a62.png) but in react-native-keychain 3.1.1 definitely I can see getSecurityLevel

**Comment by mandrigin** [comment]
@janet-rivas I think that is https://github.com/oblador/react-native-keychain/issues/193, just update the SDK version you compile with and it should go away.

**Comment by mandrigin** [comment]
@vonovak sure, I will take a look later this week.

**Comment by vonovak** [comment]
I actually thought @janet-rivas could do that, as he's apparently using TS and can test it right away. @janet-rivas do you think you could provide a fix for the TS typings? It would be appreciated.

**Comment by janet-rivas** [comment]
@vonovak  sorry I was busy but I'm retaking this issue, I'm using Android Studio and building React native app,  and that error comes from logcat, I tried to update TS file but It did not work for me, I also updated to  react-native-keychain@3.1.1 and update compileSdkVersion = 28 and  targetSdkVersion = 28 the other errors are gone and I'm able to build the app, but my credentials are not storing.

react-native-keychain.d.ts
 ```
//Adding...
function getSecurityLevel(
    ): Promise<string>; 

/*I see that enum value is returning from java public enum SecurityLevel { no sure how to handle that part*/

```
I'm thinking to use directly RNKeychainManager

**Comment by janet-rivas** [comment]
At the end   I could get getSecurityLevel the value in this "react-native-keychain": "3.1.1" version
