### ISSUE TITLE
How do you extract data from Keychain.getGenericPassword()

### ISSUE THREAD

**Issue by ThomasSchuIz** [oblador/react-native-keychain#204]
Hey guys. I'm currently storing a user name & password inside of Keychain.setGenericPassword()

`Keychain.setGenericPassword(username, passCode)`

I'm trying to retrieve this data to authenticate a user when they enter the app a second time, but I can't seem to fetch the stored variables.

`Keychain.getGenericPassword()
      .then(credentials => {
        const { username, password } = credentials
        if (username === ' ' && password === passCode) {
          AlertIOS.alert('Login successful')
        } else {
          AlertIOS.alert('Try again')
        }
      })`

But for some reason when I attempt to compare password with passCode, I get the error: 

Property 'password' does not exist on type 'boolean | { service: string; username: string; password: string; }'

Is there a way to retrieve this information?

**Comment by c6thomas** [comment]
Nobody actively working on this anymore?

**Comment by c6thomas** [comment]
Is anybody still working on this?

**Comment by Rutheniceye92** [comment]
I used the following code and saved the creds in state. Run the function to retrieve credentials in `componentDidMount()` block.
```
componentDidMount(){
    console.log('Component Mounted..!!');
    this.retrieveKeystore();
  }
  
  retrieveKeystore = async () => {
     try {
        // Retreive the credentials
        const credentials = await Keychain.getGenericPassword();
        if (credentials) {
          console.log('Credentials successfully loaded for user ' + credentials.username);
          this.setState({
            email: credentials.username,
            password: credentials.password
          })
        } else {
          console.log('No credentials stored')
        }
      } catch (error) {
        console.log('Keychain couldn\'t be accessed!', error);
      }
      await Keychain.resetGenericPassword()
  }
```
Hope it helps..

**Comment by vonovak** [comment]
hi! please open a new issue with a runnable repro (https://stackoverflow.com/help/reprex), thanks!
