### ISSUE TITLE
Android crash - RNKeychainManager.setInternetCredentialsForServer got 6 arguments, expected 7

### ISSUE THREAD

**Issue by jpapillon** [oblador/react-native-keychain#205]
### Description
When I call setInternetCredentials("server", "username", "password") on Android, I get this error: RNKeychainManager.setInternetCredentialsForServer got 6 arguments, expected 7.

<img width="431" alt="Screen Shot 2019-03-20 at 9 20 07 AM" src="https://user-images.githubusercontent.com/3585712/54688065-53814580-4af3-11e9-93dc-a49d91adf026.png">

### Additional Information
react-native-image-picker version: 3.1.1
React Native version: 0.59.1
Platform: Android
Development Operating System: MacOS

**Comment by DalbirKaur** [comment]
Any update on this?

**Comment by nileshprajapati007444** [comment]
I have same issue..

**Comment by DalbirKaur** [comment]
> Any update on this?

I am still getting the same error. Fix???

**Comment by vonovak** [comment]
hi! please try rebuilding the project and if that doesn't help, open a new issue with a runnable repro, thanks!
