### ISSUE TITLE
Android crash on API 19 on release 3.1.1

### ISSUE THREAD

**Issue by TomBerriot** [oblador/react-native-keychain#206]
Older android devices crash on react-native-keychain 3.1.1 (for any react-native version, i tested on 0.57, 0.58 and 0.59).

I tested this bug on an emulator on API 19 - 4.4.2, and on a real device of a user - 4.4.4.

Just init a new project with latest react native version and link react-native-keychain 3.1.1 to test this.

The bug occurs on the app start up, it is uneeded to call rn-keychain javascript apis to reproduce the bug.

Logcat output of the error :

![Screen 1](https://user-images.githubusercontent.com/11588007/55324827-85938f80-5483-11e9-997e-b382c062900a.png)

![Screen 2](https://user-images.githubusercontent.com/11588007/55324820-7f051800-5483-11e9-8729-1b6242951ab7.png)

**Comment by moneymc** [comment]
Same problem.
@TomBerriot did find solution?

**Comment by TomBerriot** [comment]
@moneymc Nop, we just revert our version of react-native-keychain to 3.0.0 for now

**Comment by astapinski** [comment]
I've hit this error in our app as well, I've made a PR to try and deal with it FYI https://github.com/oblador/react-native-keychain/pull/209

**Comment by astapinski** [comment]
FYI the PR landed on master now, so you can try using yarn to add the master branch for this package and it should fix the issue. You may want to confirm it as well before a release gets made.

**Comment by TomBerriot** [comment]
@astapinski Nice work thank you ! I'll try this asap :)

**Comment by TomBerriot** [comment]
@astapinski The fix works on my end ! Good job :)

**Comment by astapinski** [comment]
@TomBerriot  It looks like this made it into release 3.1.2 and 3.1.3 (latest) would have it as well, so try that out and I guess this issue should be closed.

**Comment by vonovak** [comment]
closing as fixed
