### ISSUE TITLE
RCTBridgeModule.h not found when trying to build

### ISSUE THREAD

**Issue by zaakzaku** [oblador/react-native-keychain#207]
Help me
i'm using : "react-native": "^0.59.2",   "react-native-keychain": "^3.0.0-rc.3",   
<img width="730" alt="Screenshot 2019-04-09 at 12 34 56 PM" src="https://user-images.githubusercontent.com/23735741/55773592-eba39680-5ac3-11e9-8cb9-344692c814ec.png">

**Comment by vonovak** [comment]
hi! please open a new issue with a runnable repro, thanks!
