### ISSUE TITLE
iOS crash / RNKeychainManager.setGenericPasswordForOptions got 4 arguments, expected 3

### ISSUE THREAD

**Issue by t0m0120** [oblador/react-native-keychain#212]
When I call setGenericPassword("usernamexxx", "passwordxxx", {accessGroup: xx.xx.xx, service: yy.yy.yy}) on iOS Simulator,
 I get this error but on devices no errors occur

<img src='https://user-images.githubusercontent.com/34805701/57669983-388d0680-7648-11e9-9e17-420288fd66bf.png' width='40%'>

react-native-keychain version: 3.1.1
React Native version: 0.57.8
Platform: iOS
Development Operating System: MacOS

**Comment by vonovak** [comment]
hi! please make sure to rebuild your project.

**Comment by t0m0120** [comment]
@vonovak 
Rebuild does not solve the problem

**Comment by vonovak** [comment]
@t0m0120 then please add a runnable repro, thanks.

**Comment by andrewtelkamp** [comment]
Any updates on this?

**Comment by vonovak** [comment]
@andrewtelkamp if you're running into this issue, please open a new one and include a runnable repro, thanks.
