### ISSUE TITLE
Flow error with `getGenericPassword`

### ISSUE THREAD

**Issue by Seterplus** [oblador/react-native-keychain#214]
https://github.com/oblador/react-native-keychain/blob/d8ed753383abdde35879377fd3f9760f8f3eaaeb/index.js#L214

Shouldn't it be `Promise<false | SharedWebCredentials>`?

**Comment by skovhus** [comment]
Fixed in https://github.com/oblador/react-native-keychain/pull/223

But this isn't released yet.

**Comment by vonovak** [comment]
this is now released, thanks for reporting
