### ISSUE TITLE
[Error] The specified item already exists in the keychain

### ISSUE THREAD

**Issue by PeterKruzlics** [oblador/react-native-keychain#216]
Hello,

I'm on v3.1.3 and getting the following error:
in console:
<img width="743" alt="Screen Shot 2019-05-31 at 10 25 58 AM" src="https://user-images.githubusercontent.com/6665648/58712505-b06c6800-838e-11e9-8fe7-4b5639b101e5.png">
in simuator:
<img width="355" alt="Screen Shot 2019-05-31 at 11 01 44 AM" src="https://user-images.githubusercontent.com/6665648/58714801-86697480-8393-11e9-9393-2a5e89ef54b6.png">

Here is the code that sets the value:
```js
const setItemAsync = async (key: string, value: string) => {
  try {
    const existingValue = await Keychain.getInternetCredentials(key);
    console.log('existingValue', existingValue);
    const output = await Keychain.setInternetCredentials(key, key, value);
    return output;
  } catch (error) {
    console.error('setItemAsync error:', error);
  }
};
```

I've been trying to `resetInternetCredentials` before setting it to avoid the "already exists" error, but I was still getting the error.

Am I misunderstanding how to implement this? We are using this to store Access and Refresh OAuth tokens:
```js
export const storeAccessToken = (data: string): Promise<void> =>
  SecureStore.setItemAsync(TOKEN_KEY, JSON.stringify(data));

export const storeRefreshToken = (data: string): Promise<void> =>
  SecureStore.setItemAsync(REFRESH_TOKEN_KEY, JSON.stringify(data));
```
(the flow types may be wrong, but just ignore those)

Any help would be appreciated, and please let me know if there's any additional info I should provide.

Thanks!
Peter

**Comment by PeterKruzlics** [comment]
This may be an implementation issue on our end; we have multiple API responses coming back at the same time, so it's possible that on process is `await`ing the response of the `setItemAsync` as another one kicks off (throwing the error above). Just a hypothesis for now

**Comment by mptorz** [comment]
How should I handle this error? I am getting it very often

**Comment by PeterKruzlics** [comment]
@mptorz we added a cached value that we check before reading/writing to the keychain; if I remember correctly this issue was when we would try to rapidly read/write numerous times to the keychain. That being said, I don't believe it's completely fixed for us (but does not happen as often)
