### ISSUE TITLE
null is not an object (evaluating 'RNKeychainManager.SECURITY_LEVEL_ANY')

### ISSUE THREAD

**Issue by sfmedion** [oblador/react-native-keychain#221]
`null is not an object (evaluating 'RNKeychainManager.SECURITY_LEVEL_ANY')`
`react-native-keychain@3.1.3`

![Simulator Screen Shot - iPhone X - 2019-06-26 at 13 27 54](https://user-images.githubusercontent.com/5712752/60172990-7c158b80-9816-11e9-874e-538426e95b5b.png)

**Comment by vonovak** [comment]
please make sure the module is linked correctly; follow manual installation instructions if necessary

**Comment by sfmedion** [comment]
@vonovak you were right. Using manual installation fixed the problem.

**Comment by bigchamp** [comment]
It is not linking problem, just add this:
`export const SECURITY_LEVEL = Object.freeze({
  ANY: RNKeychainManager && RNKeychainManager.SECURITY_LEVEL_ANY,
  SECURE_SOFTWARE: RNKeychainManager && RNKeychainManager.SECURITY_LEVEL_SECURE_SOFTWARE,
  SECURE_HARDWARE: RNKeychainManager && RNKeychainManager.SECURITY_LEVEL_SECURE_HARDWARE,
});`

**Comment by qiqo** [comment]
> export const SECURITY_LEVEL = Object.freeze({ ANY: RNKeychainManager && RNKeychainManager.SECURITY_LEVEL_ANY, SECURE_SOFTWARE: RNKeychainManager && RNKeychainManager.SECURITY_LEVEL_SECURE_SOFTWARE, SECURE_HARDWARE: RNKeychainManager && RNKeychainManager.SECURITY_LEVEL_SECURE_HARDWARE, });

@bigchamp's recommendation is the correct answer. I was experiencing the same issue but using this modification in the index.js file fixed it.

**Comment by donzthefonz** [comment]
> > export const SECURITY_LEVEL = Object.freeze({ ANY: RNKeychainManager && RNKeychainManager.SECURITY_LEVEL_ANY, SECURE_SOFTWARE: RNKeychainManager && RNKeychainManager.SECURITY_LEVEL_SECURE_SOFTWARE, SECURE_HARDWARE: RNKeychainManager && RNKeychainManager.SECURITY_LEVEL_SECURE_HARDWARE, });
> 
> @bigchamp's recommendation is the correct answer. I was experiencing the same issue but using this modification in the index.js file fixed it.



> It is not linking problem, just add this:
> `export const SECURITY_LEVEL = Object.freeze({ ANY: RNKeychainManager && RNKeychainManager.SECURITY_LEVEL_ANY, SECURE_SOFTWARE: RNKeychainManager && RNKeychainManager.SECURITY_LEVEL_SECURE_SOFTWARE, SECURE_HARDWARE: RNKeychainManager && RNKeychainManager.SECURITY_LEVEL_SECURE_HARDWARE, });`

Can you give an example of how/where to put this? I tried chucking it in index.js but still failing to build.
`import { registerRootComponent } from 'expo';
import App from './App';

export const SECURITY_LEVEL = Object.freeze({ ANY: RNKeychainManager && RNKeychainManager.SECURITY_LEVEL_ANY, SECURE_SOFTWARE: RNKeychainManager && RNKeychainManager.SECURITY_LEVEL_SECURE_SOFTWARE, SECURE_HARDWARE: RNKeychainManager && RNKeychainManager.SECURITY_LEVEL_SECURE_HARDWARE });

registerRootComponent(App);
`

**Comment by PoulsQ** [comment]
@donzthefonz did you find a solution to that ? I'm having the same issue here ...

**Comment by ricechenghk** [comment]
I have the same problem too...

**Comment by hengkx** [comment]
same issue

**Comment by vonovak** [comment]
hello folks, please open a new issue with a runnable repro if you're still facing this problem, thanks
