### ISSUE TITLE
Android setInternetCredentials does not resolve

### ISSUE THREAD

**Issue by kjulin** [oblador/react-native-keychain#23]
The promise returned from setInternetCredentials call does not seem to resolve when using on Android. Should there be callback.invoke() on KeychainModule.java after line 67?

**Comment by vonovak** [comment]
Indeed, that seems to be a mistake on my part. Will fix.

**Comment by vonovak** [comment]
Can you use try code from my Android_2 branch and report if it works?
Thanks

**Comment by kjulin** [comment]
@vonovak that android_2 branch of your fork works nicely in my setup. 👍

**Comment by oblador** [comment]
👍 

@vonovak: Care to do a PR? Also would you be interested in helping out as a maintainer?

**Comment by vonovak** [comment]
#24 
yes, I would

**Comment by oblador** [comment]
Merged and released as 0.3.1.
