### ISSUE TITLE
Prompt for Touch ID not working for some users

### ISSUE THREAD

**Issue by balsloev** [oblador/react-native-keychain#231]
Some of my users is reporting that Touch ID authentication is not prompting, even though Touch ID is enabled and is working on other apps.

I have not been able to reproduce this error on my own test devices, but 10+ users have reached out to me about this error. 

**The problem has been seen on the following devices:** 
- iPhone 6S
- iPhone 8 with iOS 12.3.1
- iPhone SE with iOS 12.3.1
- iPhone 5S 

It must be some kind of setting on the users phone or a general error in `react-native-keychain`

I am using:
react-native-keychain: 3.1.3
react-native: 0.59.3

This is how I save the password:
```
setGenericPassword(username, password, {
      // Constraint to access the item with biometrics for any enrolled fingers og faces
      accessControl: ACCESS_CONTROL.BIOMETRY_ANY,
      // The data in the keychain item can be accessed only while the device is unlocked by the user
      accessible: ACCESSIBLE.WHEN_UNLOCKED
});
```

Have anyone experienced this error before?

**Comment by balsloev** [comment]
I'm closing this. It was probably caused by users misunderstanding the feature.

**Comment by waheedakhtar694** [comment]
@balsloev what's the conclusion on this?  can you please also explain a bit, I also want to trigger authentication and it's not working while setGenericPassword method is called.
