### ISSUE TITLE
Argument type for functions such as `getGenericPassword` 

### ISSUE THREAD

**Issue by zoeyzou** [oblador/react-native-keychain#242]
Hi maintainers

So as in the typing file attached in the project shows that the argument for `getGenericPassword`, `setGenericPassword`, and `requestGenericPassword` include `options?: Options` type; however, in DefinitelyTyped it includes `serviceOrOptions?: string | Options`. In the use case, there's a need to pass in `string` type, but in the project (which is more well-maintained) it removed the string type. Is that a mistake or is there any way to make it work?

**Comment by zoeyzou** [comment]
Hi anybody to answser the question?

**Comment by vonovak** [comment]
hello, our typings are correct, `service` is of type `options?: Options`.
