### ISSUE TITLE
Android not storing password. iOS and Android won't prompt for biometric auth

### ISSUE THREAD

**Issue by Volksfeld** [oblador/react-native-keychain#252]
When using the following code, iOS works perfectly, but something strange happens with Android: 

I get confirmation that de credentials where stored, but when logging out, reopening the app and entering the form where the keychain is implemented, i receive the "No stored credentials response". 

I believe this happens because of the accessControl and accessible params.

```
 await setGenericPassword( email, password {
        service: 'service',
        accessControl: 'BiometryAny',
        accessible: 'AccessibleWhenPasscodeSetThisDeviceOnly',
      },
   );
```

Upon removing those params, Android manages to store the credentials, but both iOS and Android stops prompting for user biometric authentication. 

Is there a way to authenticate that works on both platforms?

**Comment by aeirola** [comment]
As mentioned in the [documentation](https://github.com/oblador/react-native-keychain#options), the `accessControl` option is for iOS only. The library doesn't support fingerprint authentication for Android at the moment. There is work being done to add this functionality, but the implementation is not yet complete.
