### ISSUE TITLE
Making the API generic

### ISSUE THREAD

**Issue by vladinator1000** [oblador/react-native-keychain#267]
I'd like to store other things, not just usernames and passwords. Would it be viable to try and add some more methods that let you store any key-value pair? Here's an example https://github.com/talut/rn-secure-storage

**Comment by vonovak** [comment]
@vladinator1000 what kind of things would you like to store? You should be able to serialize what you need to a json string and store that as a workaround

**Comment by mwss1996** [comment]
I am searching for a lib to store OpenID JSON Web Tokens, for example.

**Comment by mtt87** [comment]
> I am searching for a lib to store OpenID JSON Web Tokens, for example.

As the JWT is a string you can store it straight away, just give it a name, i.e.
```js
const accessToken = 'ey12312313131...';
await Keychain.setInternetCredentials(
    'access_token_websiteX',
    'access_token_websiteX',
    accessToken,
);

const { password } = await Keychain.getInternetCredentials('access_token_websiteX');

// password  = accessToken = 'ey12312313131...' 
```

**Comment by vonovak** [comment]
closing as this seems resolved. You can create your own utility functions around keychain functions and stored object serialized to json.
