### ISSUE TITLE
getGenericPassword not return promise

### ISSUE THREAD

**Issue by webforuse** [oblador/react-native-keychain#280]
call getGenericPassword not return Promise it just returns the credentials

My code is very simple:

await Keychain.setGenericPassword('demo', 'demo', {
      accessControl: Keychain.ACCESS_CONTROL.BIOMETRY_CURRENT_SET,
    });

Keychain.getGenericPassword().then((data) => {
      console.log('BIO-DATA', data);
    });

result: console.log('BIO-DATA', {service: "com.application", username: "demo", password: "demo"}
There is no request for either TouchID or FaceID

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 689.89 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-18 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by aeirola** [comment]
The code you provided does show that the `getGenericPassword` call in fact does return a promise, but the issue you are facing seems to be that the promise resolves immediately, without a biometric prompt.

Currently biometric authentication is only supported when running on iOS and iPadOS devices. This means that biometric authentication on iOS simulators and all Android devices do not work at the moment.

**Comment by webforuse** [comment]
> The code you provided does show that the `getGenericPassword` call in fact does return a promise, but the issue you are facing seems to be that the promise resolves immediately, without a biometric prompt.
> 
> Currently biometric authentication is only supported when running on iOS and iPadOS devices. This means that biometric authentication on iOS simulators and all Android devices do not work at the moment.

thanks.
Need to add this information to the readme
