### ISSUE TITLE
4.0.2 contains typescript issues

### ISSUE THREAD

**Issue by mtt87** [oblador/react-native-keychain#282]
1) https://github.com/oblador/react-native-keychain/pull/258/files
Forgot to change a few lines below
```ts
    export interface Options {
        accessControl?: ACCESS_CONTROL;
        accessGroup?: string;
        accessible?: ACCESSIBLE;
        authenticationPrompt?: string;
        authenticationType?: LAPolicy;   // FORGOT TO CHANGE
        service?: string;
        securityLevel? : SECURITY_LEVEL;
    }
```
```
Cannot find name 'LAPolicy'.
```

cc @petekp 

I've fixed it in this quick PR
https://github.com/oblador/react-native-keychain/pull/283

**Comment by aeirola** [comment]
Yes, 4.0.2 fixed an issue with the TypeScript typings, where they incorrectly specified that `getInternetCredentials` would always return an object, even though the implementation and documentation state that it can also return `false` in case the specified key was not found. In case your code did not already check for these cases, you might need to add code that handles the case where nothing has yet been stored for the given key.

P.S. I think it would be easier to discuss the issues if they were reported in separate issues.

**Comment by mtt87** [comment]
@aeirola you are right, that's the correct behaviour I just needed to handle the `false` case 👍 

Thanks for the clarification!

**Comment by petekp** [comment]
@mtt87 Oops 😊 — good catch, thanks for fixing!
