### ISSUE TITLE
Feature request: Android face authentication (BiometricManager)

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [oblador/react-native-keychain#287]
Hi 

First of all, thanks for the great library! 😃 It's been a pleasure to work with so far. 

As I understand it, this library doesn't yet support Android face authentication (correct me if I'm wrong!). Android [recently](https://android-developers.googleblog.com/2019/10/one-biometric-api-over-all-android.html) released biometric authentication in Android Q/10 (API version 29), which deprecates [`FingerprintManager`](https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager) which seems to be what this library is [using](https://github.com/oblador/react-native-keychain/blob/master/android/src/main/java/com/oblador/keychain/DeviceAvailability.java). `FingerprintManager` has been replaced with [`BiometricManager`](https://developer.android.com/reference/android/hardware/biometrics/BiometricManager) and [`BiometricPrompt`](https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt.html), which can be used like described in this [training tutorial](https://developer.android.com/training/sign-in/biometric-auth).

Are there any plans for supporting Android face authentication in the nearest future or is work maybe already being done?

Best regards
Jens

**Comment by OleksandrKucherenko** [comment]
https://github.com/oblador/react-native-keychain/pull/260 - is the step forward in that direction. after it merge will be possible to added implementations for face_id, PIN, passcode verifications

**Comment by oblador** [comment]
This is now possible with version 5.0.0.
