### ISSUE TITLE
setGenericPassword not showing touchId prompt

### ISSUE THREAD

**Issue by mehhh** [oblador/react-native-keychain#294]
Hello guys, great work with this library!

My issue/question is the following:
When I use setGenericPassword, example:

```
await setGenericPassword("User", "Pass", {
      service: serviceName,
      accessControl: ACCESS_CONTROL.BIOMETRY_CURRENT_SET,
      accessible: ACCESSIBLE.WHEN_UNLOCKED_THIS_DEVICE_ONLY,
      authenticationPrompt: "Are you you?",
      authenticationType: AUTHENTICATION_TYPE.DEVICE_PASSCODE_OR_BIOMETRICS
    })

```
The data is stored successfully but the prompt to confirm my fingerprint does not show. Only when retrieving the secret with `getGenericPassword(...)` does the prompt show.
This is strange for me, since for the accessControl options passcode and password, the prompt to input either my phone passcode or app password show, and I have to set them before being able to store the data.
Is there a combination of `accessControl + accessible + authenticationType` that I am missing to make the touchId/faceId prompt show before saving the data?

Simple project with: 
**react-native: v0.61.5
react-native-keychain: v4.0.5**

Running on a **physical device(iPhone 7 - TouchID enabled, fingerprint enrolled and phone unlocked with fingerprint)**, so no issues with emulator not working should not apply here.

Edit: just checked again, and actually `ACCESS_CONTROL.DEVICE_PASSCODE` has the same behaviour and does not show the prompt on set. 
So in fact the behaviour is consistent and this is not an issue. 
Closing this issue.

**Comment by waheedakhtar694** [comment]
@mehhh is this works for you?

**Comment by jeseter45** [comment]
Just for reference here: I struggled with the same. This is due to TypeScript typings incomplete design, see https://github.com/oblador/react-native-keychain/issues/426
