### ISSUE TITLE
Custom screen for application password request

### ISSUE THREAD

**Issue by onepood** [oblador/react-native-keychain#296]
Is it possible to pass to getGenericPassword() a string with the code if APPLICATION_PASSWORD is used? I would like to use custom screen to request a user password. It would be good option
if we can just pass a code in setGenericPassword and getGenericPassword methods.

**Comment by vonovak** [comment]
hello, thanks for the request. Unfortunately I don't really understand what you want. If this is still a problem, can you please open a new issue and explain more clearly? Thanks
