### ISSUE TITLE
how to store an object into the key chain?

### ISSUE THREAD

**Issue by chirag04** [oblador/react-native-keychain#3]
Is it possible to store an object into the keychain? Maybe stringify and store it as password?

**Comment by oblador** [comment]
Stringify is the only way right now. Adding it to my todo :-)

**Comment by chirag04** [comment]
i can help here if you can point me to right direction. 

Also, is this used in any production app? Need to use this in a production app. just not sure if its ready yet.

Thanks.

**Comment by oblador** [comment]
If you need it urgently you can just write a simple wrapper to stringify/parse. 

I have plans to implement larger parts of the API, some of which takes NSData which I guess is more suitable then storing it as a password. If you want to start implementing it I'd be grateful but it's probably quite a bit of work. I've started with doing enums, so you could go from there. 

I'm using this lib in my app, but that one is not yet released on the AppStore. If you're worried about maturity then you shouldn't use React Native at all, nothing is stable at this point :-)

**Comment by chirag04** [comment]
stringify/parse worked like a charm.

Cool. I will try to look at all that. Not sure if i will be able to do it. Really new to ios.

Nice to know that you using it in your app. Nah, not worried too much about maturity. Just wanted to know if anyone is using it in prod.

Thanks for all the help though. :-)

**Comment by digitaldavenyc** [comment]
Any ETA on this? Would be a nice feature

**Comment by vonovak** [comment]
closing, please use stringify / parse
