### ISSUE TITLE
Android biometric hint not translated

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [oblador/react-native-keychain#304]
The biometric prompt on Android shows "Touch the fingerprint sensor". Changing the system language doesn't change the text. It [looks](https://stackoverflow.com/a/60542681/3749432) as if the Android biometric library comes with support for all languages, but I doesn't seem to work. Am I doing something wrong?

I downgraded `androidx.appcompat:appcompat` from version 1.1.0 to 1.0.2 based on some other suggestions, and it made it somewhat work: 
![biometric](https://user-images.githubusercontent.com/28528363/75973189-0d282080-5ed5-11ea-9d36-f95cc8b15282.jpg)

But now I can't turn it back to English again by changing the system language...

**Comment by oblador** [comment]
Fixed by #302

**Comment by jenskuhrjorgensen** [comment]
Hi @oblador 
Are you sure that #302 actually fixes this issue? This issue is regarding the hint text not being translated and not the android `PromptInfo`.
