### ISSUE TITLE
Custom biometrics authentication screen

### ISSUE THREAD

**Issue by Mike-Van** [oblador/react-native-keychain#308]
The package works great. But im just wondering if there's any way we can use custom screen or custom component when triggering biometrics authentication. For example, i want to build my own custom fingerprint scanner scren, and let package do the verification listening in the background.

**Comment by taeingyu** [comment]
`androidx.biometric.BiometricPrompt` is used for user interaction, I think it'd be good to support `authenticationPrompt` property first for internationalization.

https://github.com/oblador/react-native-keychain/blob/c854720a8945990dc75bbfbd02dc2044bda8aead/android/src/main/java/com/oblador/keychain/KeychainModule.java#L834-L838

**Comment by jenskuhrjorgensen** [comment]
@taeingyu There is a PR for this already: https://github.com/oblador/react-native-keychain/pull/302

**Comment by oblador** [comment]
Mentioned PR is now merged and thus closing this issue

**Comment by quanlh-ttlab** [comment]
Is there a way to listen to the fingerprint, faceid authentication event cause I want to customize the screen when authenticating?
