### ISSUE TITLE
libRNKeychain.a(RNKeychainManager.o)) was built for newer iOS version (8.3) than being linked (7.0)

### ISSUE THREAD

**Issue by chenxsan** [oblador/react-native-keychain#31]
When built my app in xcode, I got the error:

> libRNKeychain.a(RNKeychainManager.o)) was built for newer iOS version (8.3) than being linked (7.0)

Can I use react-native-keychain when targeting iOS 7?

I tested it on iOS 7 simulator, it worked as expected, need a confirm here.

**Comment by tminard** [comment]
Same here... Build error.

**Comment by SudoPlz** [comment]
Same here..!

**Comment by vonovak** [comment]
closing as we moved deployment target to 9.0 #155
