### ISSUE TITLE
iOS 10 requires "Keychain Sharing" to be enabled

### ISSUE THREAD

**Issue by sventschui** [oblador/react-native-keychain#32]
I'd recommend to add a note to the README that iOS 10 currently requires "Keychain Sharing" to be enabled (See https://forums.developer.apple.com/thread/60617). Otherwise one will experience the following Issue:

```
Error: {
    code = "-34018";
    domain = NSOSStatusErrorDomain;
    message = "The operation couldn\U2019t be completed. (OSStatus error -34018.)";
}
```

![screen shot 2016-09-16 at 20 52 14](https://cloud.githubusercontent.com/assets/512692/18597819/03ee70de-7c50-11e6-9eac-af66aacf582a.png)

![screen shot 2016-09-16 at 20 56 33](https://cloud.githubusercontent.com/assets/512692/18597833/15316342-7c50-11e6-92e7-781651e61563.png)

**Comment by oblador** [comment]
Thanks @sventschui 👍, can you do a PR with your proposed changes?

**Comment by vaibhawc** [comment]
Hey guys thanks for this awesome library. 
I am facing some issues on user side which I am unable to reproduce on my side. 
So I was exploring the set of problems related to keychain.
Could you please point me or tell me when (using which functions of the library) 
such an error may occur, and when it will definitely not occur. 
I don't understand keychain completely.
