### ISSUE TITLE
[Error: I/O error: javax.crypto.IllegalBlockSizeException: input must be under 384 bytes]

### ISSUE THREAD

**Issue by Bautista-Baiocchi-lora** [oblador/react-native-keychain#334]
Hello,

I am getting a BlockSizeException when calling setInternetCredentials. 

Code causing it.
```
export const saveToken = async (user: string, newToken: string) => {
  token = newToken;
  return await Keychain.setInternetCredentials(
    SERVER,
    user,
    token,
  ).catch((error) => console.log(error));
};
```

This only happens on android if my token is bigger than 384 bytes (which isn't much..).
I am running this on an android 9 device.

**Comment by ioannisGiak89** [comment]
After following https://github.com/oblador/react-native-keychain#important-behavior the issue was fixed

**Comment by Bautista-Baiocchi-lora** [comment]
> After following https://github.com/oblador/react-native-keychain#important-behavior the issue was fixed

Sorry, I am not sure which part of that you followed. It doesn't seem to address the error directly. Would you mind explaining further?

**Comment by Bautista-Baiocchi-lora** [comment]
Was able to fix the issue on android using `storage: Keychain.STORAGE_TYPE.AES` option when saving internet credentials.
