### ISSUE TITLE
[iOS] SecItemAdd() -- The dictionary does not specify a value for kSecAttrAccessible key

### ISSUE THREAD

**Issue by aprct** [oblador/react-native-keychain#35]
It's setting off some flags for sanity checks in our company's static code security scanner:

> **Attack Vector:** SecItemAdd
> **Description:** In this call to SecItemAdd(), the dictionary specified does not appear to include a value for the key kSecAttrAccessible. This value defaults to kSecAttrAccessibleWhenUnlocked, which may result in keychain data being accessible and unlocked longer than necessary.
> **Remediation:** Review the potential values for kSecAttrAccessible, and ensure that the one used in this application meets the security needs of its users.
> **References:** [CWE](http://cwe.mitre.org/data/definitions/522.html)  [Apple Keychain Ref](https://developer.apple.com/reference/security/1658642-keychain_services/1663541-keychain_item_accessibility_cons)

I know it's an issue of semantics, but it would be nice if this setting was either exposed in the JS module, or set explicitly to the default value: [https://developer.apple.com/reference/security/ksecattraccessiblewhenunlocked](https://developer.apple.com/reference/security/ksecattraccessiblewhenunlocked)

Thanks :)

**Comment by oblador** [comment]
Accessibility option is now supported in [1.1.0](https://github.com/oblador/react-native-keychain/releases/tag/v1.1.0).
