### ISSUE TITLE
getInternetCredentials fails with error message "subtitle"

### ISSUE THREAD

**Issue by hsjoberg** [oblador/react-native-keychain#353]
Hi!
I am saving data with `setInternetCredentials` using `accessible: Keychain.ACCESSIBLE.WHEN_UNLOCKED` as the sole property into the options argument, nothing else. I need the data to be accessible without any prompt or biometrics reading at all.

Since 6.1.0, `getInternetCredentials` fails with "subtitle" as the error message.
If I add `authenticationPrompt` to options in `getInternetCredentials` it does work, but it doesn't make any sense to do that since no prompt is required or wanted to reach the data. 

I've tried reverting back to 6.0.0 and it seems to work fine there.

This is on Android.

Best
Hampus

**Comment by hsjoberg** [comment]
My guess would be that this is caused by the refactoring and creation of a PromptInfoHelper in fa4ad3c9cf7e7f8e895960a2997eff1f97ec86e1.
It does not make the same checks if it can use the subtitle prop and other properties as the old code would do: https://github.com/oblador/react-native-keychain/commit/fa4ad3c9cf7e7f8e895960a2997eff1f97ec86e1#diff-a7f0938e34b4927ca794e0ac8b94ebe3

The current authenticationPrompt defaults does not have a subtitle: https://github.com/oblador/react-native-keychain/blob/7b19e8dfc3d7bcf9758e88d83d52692c5937d1f3/index.js#L116-L119

**Comment by ravi-poonia** [comment]
Facing the same issue with getGenericPassword, 
RN version 0.62.2

**Comment by oblador** [comment]
Reverted supposed test fixes and released [6.1.1](https://github.com/oblador/react-native-keychain/releases/tag/v6.1.1), please test and verify that it fixes the problem.

**Comment by nvojnovic** [comment]
Thanks Joel, this issue is fixed in [6.1.1](https://github.com/oblador/react-native-keychain/releases/tag/v6.1.1)

**Comment by hsjoberg** [comment]
6.1.1 works for me too.
