### ISSUE TITLE
Property 'password' does not exist on type 'false | SharedWebCredentials'.

### ISSUE THREAD

**Issue by AndriiBoiko** [oblador/react-native-keychain#358]
Hi!
I have got the error from typescript 
**Property 'password' does not exist on type 'false | SharedWebCredentials'.**
```
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-keychain": "^6.1.1",
```
```
    try {
      const credentials = await Keychain.getGenericPassword();
      if (!credentials) {
           return;
      }
      const { password } = credentials;

    } catch (err) {
    }
```

**Comment by javier-tw** [comment]
This is due to TS doesnt know that you are already checking that the credentials are not false, in your use case, you can use an "else" statement in order to indicate it to TS like:

    try {
      const credentials = await Keychain.getGenericPassword();
      if (!credentials) {
           return;
      } else {
           const { password } = credentials;
     }

    } catch (err) {
    }

I personally encapsulate this behaviour with the TS 'is' helper:

    const isValidCredentials = (c): c is SharedWebCredentials => c && c.username === 'credentials'

    export async function load(): Promise<Credentials | null> {
        const credentials = await ReactNativeKeychain.getGenericPassword()
        return isValidCredentials(credentials) ? JSON.parse(credentials.password) : null
     }

Hope this works for you :)

**Comment by AndriiBoiko** [comment]
@javier-tw Thx!
I will try
