### ISSUE TITLE
Error on try to setGenericPassword on iPad

### ISSUE THREAD

**Issue by lucaashrq** [oblador/react-native-keychain#362]
Hi guys,

I implemented this library in my app and all works fine in Android and iOS smartphones.
But, specifically on the iPad when i try to use the **setGenericPassword** with my options, i get the following error back:

> The user name or passphrase you entered is not correct.

Before i try to use setGenericPassword i verify if the device can imply authentication with **canImplyAuthentication**, and the return is true.

Am I missing something?
Every help is welcome.

**Comment by CWolfs** [comment]
I had this error when I hadn't set a TouchID (or FaceID) up. I enrolled one of my fingers in the iPhone and then it worked for TouchID for me.
