### ISSUE TITLE
Shared Web Credentials support?

### ISSUE THREAD

**Issue by messense** [oblador/react-native-keychain#37]
https://developer.apple.com/reference/security/1654440-shared_web_credentials

**Comment by oblador** [comment]
I think that should work out of the box yes, but I haven't tried.

**Comment by messense** [comment]
It needs to call [SecAddSharedWebCredential(_:_:_:_:)](https://developer.apple.com/reference/security/1617986-secaddsharedwebcredential) and/or [SecRequestSharedWebCredential(_:_:_:)](https://developer.apple.com/reference/security/1617896-secrequestsharedwebcredential), I can't find them in current codebase.

**Comment by messense** [comment]
FYI: [Shared web credentials: A simpler way to log in](https://engineering.pinterest.com/blog/shared-web-credentials-simpler-way-log)

**Comment by oblador** [comment]
Ah, ok. I would merge a PR with this feature :-)

**Comment by oblador** [comment]
@messense Please review my PR with this functionality.
