### ISSUE TITLE
Pixel 4 support?

### ISSUE THREAD

**Issue by dafuga** [oblador/react-native-keychain#371]
Hey guys,

I am using this library (v 6.1.1) in my RN app like this:

```
import RNKeychain, {
  ACCESS_CONTROL,
} from 'react-native-keychain';

const config = {
  accessControl: ACCESS_CONTROL.BIOMETRY_ANY_OR_DEVICE_PASSCODE,
};

await RNKeychain.setInternetCredentials('keyName', 'publicKey', 'privateKey', config);

const { password: privateKey } = await RNKeychain.getInternetCredentials('keyName');

console.log({privateKey})
```
and it works great on most phones, but when I try to test it on my Pixel 4, `getInternetCredentials` just never resolves the promise and the password is therefore not returned. Was wondering if the Pixel 4 is not currently supported and if so do you plan on adding support for it in the near future?

Thanks!

**Comment by aeirola** [comment]
Hi @dafuga we've identified a regression in the latest versions of the library which cause issues with fingerprint authentication on Pixel devices with the Titan M security chip. We have a preliminary fix for this in #385 which we are still testing to make sure it works well. If you want to help get the fix released soon, we'd ask you to test out the code in the PR with your pixel device in your scenario and report results. The code can be installed directly with `npm install github:cshfang/react-native-keychain#fix-strongbox-decryption`. Thanks.

**Comment by danna88** [comment]
hi，when you do getInternetCredentials() on Pixel 4,what do you get?  it return false?

**Comment by pi-xel** [comment]
Hi, ai am on v6.2.0 but nevertheless experiencing an issue with a Pixel 3a. `getGenericCredentials` returns a `Could not decrypt data with alias: x` exception. I did not see this on any other devices, so I reckon it could be related.

Do you have any idea what the issue could be? Thanks in advance.

**Comment by dafuga** [comment]
I can confirm that the the library now works with pixel 4 face id. Thanks!
