### ISSUE TITLE
Service name and access group configuration

### ISSUE THREAD

**Issue by isair** [oblador/react-native-keychain#4]
Is there currently a way to specify the keychain service name and access group to use in this module?

**Comment by oblador** [comment]
`setGenericPassword` takes an optional third argument for service name, but access group is yet to be implemented. I just have too much other work to do right now, but it's on my todo.

**Comment by tsteele2013** [comment]
I may take a stab at this.

**Comment by maxperry** [comment]
Please see my PR #54

**Comment by dcalhoun** [comment]
@oblador I haven't tested whether it works, but based on your work in 45799d5, this issue should likely be closed. Just figured it might be helpful to clean up now irrelevant issues.

**Comment by vonovak** [comment]
this is implemented
