### ISSUE TITLE
[Android] setGenericPassword not working on Samsung devices: "Attempt to invoke virtual method 'getPublicKey()' on a null object reference"

### ISSUE THREAD

**Issue by SocialBrothersDEV** [oblador/react-native-keychain#403]
First of all, thanks for this library. It has helped me a lot already.

However, i am running into an issue on Samsung devices when calling `setGenericPassword()`.

I am currently invoking the method  like this:

```
Keychain.setGenericPassword('general', value, {
    accessible: Keychain.ACCESSIBLE.WHEN_UNLOCKED,
    accessControl:
      hasBiometrics && isBiometricsProtected
        ? Keychain.ACCESS_CONTROL.BIOMETRY_CURRENT_SET_OR_DEVICE_PASSCODE
        : undefined,
    service: username ? `${service}_${username}` : service,
  });
```

However when i do this i am getting this error on Android:

```
Error: Unknown error: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
    at Object.promiseMethodWrapper [as setGenericPasswordForOptions] (NativeModules.js:103)
    at Object.setGenericPassword (index.js:179)
    at setKeychain$ (Storage.ts:37)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:154)
    at runtime.js:164
    at tryCallOne (core.js:37)
```

Please let me know how i can fix this, my app is going to production soon.

**Comment by AlexD10S** [comment]
Hi,
I am getting this error too, in my case in a Xiaomi.
Did you find the solution?

**Comment by oferRounds** [comment]
Seeing it also

**Comment by oferRounds** [comment]
Hi @AlexD10S, did you find any solution to this?

**Comment by SocialBrothersDEV** [comment]
I have eventually removed this library from my project and moved to Expo's [SecureStore](https://docs.expo.io/versions/latest/sdk/securestore/) and [LocalAuthentication](https://docs.expo.io/versions/v39.0.0/sdk/local-authentication/) libraries. I would love to come back to this library once this is fixed tho.

**Comment by oferRounds** [comment]
Thanks @SocialBrothersDEV!
(I’m not using expo, so that won’t work for me)

**Comment by Perolini** [comment]
I have the same problem on Huawei

**Comment by nadishan** [comment]
I have the same problem with Nokia (API Level 29)

**Comment by fr33z3** [comment]
Any updates for this problem? Did anyone solved it?

**Comment by ObidosDev** [comment]
Same here. Samsung... Android 10, One UI 2.0

**Comment by weraaaaz** [comment]
Same for Samsung Galaxy S20 (Android 11), Samsung Galaxy S10 (Android 11), Samsung Galaxy A71 (Android 11), Samsung Galaxy S7 edge (Android 8), Nokia 7.2 (Android 10)

**Comment by Juan-Castelli** [comment]
I'm following this issue as it appears to be critical.

It is NOT happening on real device Samsung A50 with Android 10 OneUI2.5.

At least when using setGenericPassword/getGenericPassword.

Does it happen when you call it normally with no options at all? Just the service option, username and password?

**Comment by aleksterm** [comment]
Hey guys!

Got similar problem. In my app's flow, I was initially using `setGenericPassword()` without any `accessControl` option. Then I prompt user to enable biometric auth and in case he agreed I invoked `setGenericPassword()` again with the same credentials plus `accessControl` option `BIOMETRY_ANY`. And it failed with the error `Attempt to invoke virtual method...`

Through trial and errors I found out, that in that case I had to previously use `resetGenericPassword()` before storing the same credentials with `setGenericPassword()`.

If this is your case, you may give this workaround a try.

**Comment by CryptoBadBoy** [comment]
Hi

I had the problem with setInternetCredentials. But I changed setInternetCredentials to setGenericPassword and the problem disappeared.

**Comment by web3Liuwentong** [comment]
Any update? I followed @[aleksterm](https://github.com/aleksterm) advice, but still, get this error log sometimes.

**Comment by MAKARD** [comment]
well, 2023
This issue is still with us
Version 8.1.1
<img width="452" alt="image" src="https://github.com/oblador/react-native-keychain/assets/25794983/dfb0a444-534a-4986-9008-a307428a76e8">
<img width="1357" alt="image" src="https://github.com/oblador/react-native-keychain/assets/25794983/f287f592-f34a-434f-afce-4e294b92497e">

**Comment by ErickMaeda** [comment]
Hello, this issue started happening with me when using the `Keychain.setGenericPassword` with `Biometrics`

I have this set of devices that had this issue:

![Screenshot 2023-07-05 at 13 38 28](https://github.com/oblador/react-native-keychain/assets/12499837/78496fe1-c326-4e35-b883-1f60c8861901)

![Screenshot 2023-07-05 at 13 39 10](https://github.com/oblador/react-native-keychain/assets/12499837/61f0d912-5690-4848-9293-74487a1031d9)

Does anyone has an update on this issue?

**Comment by lchenfox** [comment]
The same issue on Andorid. 

```
Error: Unknown error: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
Error: Unknown error: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
```

**Comment by Dr0pG** [comment]
Any updates on this, guys?

**Comment by baontsparkminds** [comment]
Hi guys, I solved this issue by calling set/get/reset GenericPassword with the same service and making sure to reset before setting a new GenericPassword.
