### ISSUE TITLE
Error User interaction is not allowed on iOS

### ISSUE THREAD

**Issue by danwhite-ipc** [oblador/react-native-keychain#404]
When calling Keychain.getGenericPassword() I am occasionally receive a `User interaction is not allowed` error. 
The options I use when setting the item is `const options = { service, accessible: Keychain.ACCESSIBLE.ALWAYS };`

Version: 6.2.0

**Comment by PaperbagWriter** [comment]
@danwhite-ipc  You closed, reopened and closed, did you find something?

**Comment by danwhite-ipc** [comment]
The issue was a cached keychain with the wrong access, didn't realise it's not cleared on app uninstall

**Comment by dataxp** [comment]
Hi @danwhite-ipc  I'm having the same error message, how did you manage to solve the issue?

**Comment by danwhite-ipc** [comment]
I ended up just changing the key along with the updated accessibility option
