### ISSUE TITLE
[QUESTION] How to translate modal on android

### ISSUE THREAD

**Issue by mickadoua** [oblador/react-native-keychain#408]
Hello, i would like to know how can i translate the modal on android, 

If my phone is in Spanish or french, the modal stay  in English

Thansk

**Comment by CWolfs** [comment]
If you look at the example here https://github.com/oblador/react-native-keychain/blob/5441078/KeychainExample/App.js#L89 you'll see you can pass the `authenticationPrompt` option in. You provide your own translation at this point and pass the translated text into the library there.

**Comment by mickadoua** [comment]
ok thank you very-much for your help
