### ISSUE TITLE
question about android support

### ISSUE THREAD

**Issue by npomfret** [oblador/react-native-keychain#41]
Thanks for this module, looks very useful.

If I store a password in the iOS keychain I understand it would get syncd via iCloud to my other devices (if i've turned that feature on).

Does the android implementation also sync the passwords across devices?

**Comment by vonovak** [comment]
hi there!
no, the Android implementation doesn't support this. Not even sure if android has built-in functionality for this.

**Comment by npomfret** [comment]
I'm not sure it does either.  Thanks for the reply
