### ISSUE TITLE
6.2.0 - Android crash - RNKeychainManager.setInternetCredentialsForServer got 7 arguments expected 6

### ISSUE THREAD

**Issue by Turtus** [oblador/react-native-keychain#415]
after upgrade to version 6.2.0, both on emulator for android 6 and android 11

simular to https://github.com/oblador/react-native-keychain/issues/205 but rebuild not helping

previously working one call

await Keychain.setInternetCredentials(this._serviceName + '_' + key, pub, priv,

trying to fix by adding all options params - not helped

await Keychain.setInternetCredentials(this._serviceName + '_' + key, pub, priv, {

                accessControl: 'UserPresence',
                accessGroup: '',
                accessible: 'AccessibleAlways',
                authenticationPrompt: {
                    title: 'Fingerprint title',
                    cancel: 'Cancel'
                },
                authenticationType: 'AuthenticationWithBiometricsDevicePasscode',
                service: this._serviceName,
                securityLevel: 2,
                storage: 'KeystoreAESCBC',
                rules: 'none'

**Comment by Turtus** [comment]
magically not broking on real devices - only on emulators, and now even on emulators breaks not every time((( strange

**Comment by CWolfs** [comment]
Basically I never test biometrics on emulators or simulators. Just not worth the false negatives or problems.

**Comment by Turtus** [comment]
it makes a little bit "magic-drived" development of application than store some essentual data in keystore( 
i`ll close issue but hope it will be more stable when you have time

**Comment by shivchawla** [comment]
I am testing on real android device and have the same issue as @Turtus

**Comment by shivchawla** [comment]
Solved by upgrading to Android v 4.1 from v4.0 [and Gradle and Gradle build tools as suggested by android studio)
