### ISSUE TITLE
weird issue in promise

### ISSUE THREAD

**Issue by ducduong** [oblador/react-native-keychain#42]
Hello, I'm see a very weird issue.

Keychain.getGenericPassword().
   .then(cred => { this.setState(A) })
   .catch(error) { this.setState(B) }

When this.setState(A), my component will re-render something, now, if during rendering, any error happens, catch will fire and setState(B) will fire.

Is it a real issue? My understand is that setState(B) will only fire when there's no generic password. This issue is masking the real problem, for example, when rendering a component with wrong style, it just silently fail and fire setState(B).

**Comment by oblador** [comment]
You can reverse the order of `then` and `catch` to fix this, but ideally your render wouldn't throw exceptions :-)
