### ISSUE TITLE
performance problems

### ISSUE THREAD

**Issue by ghost** [oblador/react-native-keychain#420]
too slow on android while getting the data objects. AsyncStorage is very fast than this I am just simply using the example of this package as provided.

**Comment by iAmHarmon** [comment]
I am also having issues with Android being very slow. Any suggestions?

**Comment by tadasstra** [comment]
Yes, very slow keys reading when opening the app first time, is it possible to improve the reading speed at first time?

**Comment by tommeier** [comment]
https://github.com/oblador/react-native-keychain/issues/337

**Comment by oblador** [comment]
Please try out 8.0.0 which has performance improvements
