### ISSUE TITLE
TypeScript Options interface is used in contrary to the docs

### ISSUE THREAD

**Issue by ghost** [oblador/react-native-keychain#426]
TypeScript interface [`Options`](https://github.com/oblador/react-native-keychain/blob/55753f686c0c1374afe4e5df19943f2c003219fd/typings/react-native-keychain.d.ts#L74) is shared throughout the whole API, which is in contrary to the [documentation](https://github.com/oblador/react-native-keychain#api).

This small TypeScript simplification made me to struggle with understanding the API a lot, until I accidentally found correct options listings in the `README.md` file.

Can we split it properly?

**Comment by DorianMazur** [comment]
New documentation has been created. I will close this issue as it's no longer valid.
