### ISSUE TITLE
Error on setInternetCredentials

### ISSUE THREAD

**Issue by dburgmann** [oblador/react-native-keychain#43]
I am running on React Native 0.38.
Installed via npm, linked and added the keychain sharing entitlement.

However on "setInternetCredentials" i get an error saying:

> undefined is not an object (evaluating 'RNKeychainManager.setInternetCredentialsForServer')

Any idea whats the reason?
Thanks

**Comment by vonovak** [comment]
What platform are you using?
Follow the manual instructions and verify your project looks as described
in them.

**Comment by vonovak** [comment]
closed for inactivity
