### ISSUE TITLE
Android build fails on linux bionic

### ISSUE THREAD

**Issue by abrel** [oblador/react-native-keychain#431]
Hi Everyone,

I am getting the following build errors on travis using a linux bionic distribution. (On my local OSX machine the build goes perfectly)

> /home/travis/build/XXX/mobile/node_modules/react-native-keychain/android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java:32: error: CipherStorageKeystoreAESCBC is not abstract and does not override abstract method getDefaultAliasServiceName() in CipherStorage
public class CipherStorageKeystoreAESCBC implements CipherStorage {
       ^
/home/travis/build/XXX/mobile/node_modules/react-native-keychain/android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java:56: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/travis/build/XXX/mobile/node_modules/react-native-keychain/android/src/main/java/com/oblador/keychain/cipherStorage/CipherStorageKeystoreAESCBC.java:96: error: method does not override or implement a method from a supertype
    @Override
    ^
3 errors

Any clues regarding how to solve this ?

**Comment by erksch** [comment]
having the same problem, what's the fix?
