### ISSUE TITLE
Credentials Not Saving on some Android 7 Devices

### ISSUE THREAD

**Issue by thecodecafe** [oblador/react-native-keychain#437]
Hello,
Thanks for this great library, I've been facing an issue with this for the past 4 weeks now, I have an issue where after setting a username and password, in an attempt to get the set username and password, I get empty strings for both of them, this only happens on some Android 7 devices

#### My implementation

```
// This is used to set a password
await setGenericPassword(username, password, {
  accessControl: 'BiometryCurrentSetOrDevicePasscode' as any,
  accessible: 'AccessibleWhenPasscodeSetThisDeviceOnly' as any,
  authenticationPrompt: {
    title: `Instant authentication with ${hardwareName}?`,
  },
});
```
I have logged the username and password to the console after calling `setGenericPassword` and they contain the appropriate data.

```
// This is used to get the set password
const data = await getGenericPassword({
  accessControl: 'BiometryCurrentSetOrDevicePasscode' as any,
  accessible: 'AccessibleWhenPasscodeSetThisDeviceOnly' as any,
  authenticationPrompt: {
    title: `Authenticate with ${hardwareName}?`,
  },
});
```
Both `data.username` and `data.password` are empty strings after this.

React Native Version: 0.63.2
Keychain Version: 6.2.0

Is there something I am missing here? Please help, thanks!

**Comment by M-Jas** [comment]
My credentials are saving, but they are getting wiped out and I'm seeing the same result for iOS. If I do a sequence of logging in then out, on the second attempt(Keeping in mind the first attempt worked and the username + pass were not " ") the username and password are empty strings. I'm not calling `resetGenericPassword` anywhere and I'm providing a service name.

How I'm setting it:
```
  Keychain.setGenericPassword(username, pw, {
    service: 'SERVICE_BIO_AUTH',
    accessControl: Keychain.ACCESS_CONTROL.BIOMETRY_ANY,
    accessible: Keychain.ACCESSIBLE.WHEN_UNLOCKED,
  });
  ```
  
How I'm getting it:
  ```
   Keychain.getGenericPassword({
     service: 'SERVICE_BIO_AUTH',
   })
  ```

Result:
`LOGIN WITH BIO {username: '', password: '', storage: 'keychain', service: 'SERVICE_BIO_AUTH'}`
