### ISSUE TITLE
Not issue but question about the error mentioned at README

### ISSUE THREAD

**Issue by vaibhawc** [oblador/react-native-keychain#44]
Hey guys thanks for this awesome library.
I am facing some issues on user side which I am unable to reproduce on my side.
So I was exploring the set of problems related to keychain and was curious about this error:
Error: {
    code = "-34018";
    domain = NSOSStatusErrorDomain;
    message = "The operation couldn\U2019t be completed. (OSStatus error -34018.)";
}
Could you please point me or tell me when (using which functions of the library)
such an error may occur, and when it will definitely not occur?
I don't understand keychain completely.

**Comment by vonovak** [comment]
hi! See #32 
Without more information it'll hard to help

**Comment by vaibhawc** [comment]
Actually I know about it. I am more curious about that error. What goes wrong that it occurs?

**Comment by sventschui** [comment]
If you want to understand it in-depth head over to the linked apple dev forum thread https://forums.developer.apple.com/thread/60617

To sum it up: Seems to be a bug that only happens if there is no entitlement file. The "Share keychain" option seems to be required only if there is not yet an entitlements file.

See the cited answer from the forum linked above

> As others have reported, my app would always fail on SecItemAdd() with -34018 on the simulator but work fine on a device. I was about to add the 'Share keychain' entitlement as a workaround but noticed that Xcode 8 was prompting me to add the 'Push Notification' entitlement (that entitlement is now required to use push notificaitons on iOS 10 as the permission is taken from the entitlement rather than the provisioning profile in earlier versions). This *created* an entitlements file because the app didn't have one before. And without adding the 'Share keychain' entitlement the app suddenly started working! No more -34018. I've reverted back and forth and it seems pretty deterministic: no entitlements file gives -34018; entitlements file works.
>  
> So, my testing seems to show that SecItemAdd fails if there's no entitlement file, and works if there is one! Perhaps all the developers adding 'Share keychain' entitlement never had an entitlement file before and it is the creation of the file rather than the specific entitlement that fixes the problem?
