### ISSUE TITLE
Remove/Delete all keys?

### ISSUE THREAD

**Issue by pke** [oblador/react-native-keychain#467]
Is there a way to just completely clear the keychain without deleting every entry one after another?

**Comment by M1ST4KE** [comment]
@pke There is no native API allowing to clear all data of a certain app from the keychain. The only way to clear the keychain is to remove the biometry authentication method used to create entries in the keychain or to wipe the device.

**Comment by pke** [comment]
Oh ok, didn't know that. Thanks!
