### ISSUE TITLE
How can we share credentials between react native app and browser?

### ISSUE THREAD

**Issue by Tinju-joseph** [oblador/react-native-keychain#481]
I want to share login credentials from app to browser, user logged to app using there username and password. When user open app website on browser, looking any option to get username and password auto filled there.

Tried setInternetCredentials("abc.com","username","password")

Tried above on android, but didn't work.

Is it possible?

**Comment by oblador** [comment]
The API you want is `requestSharedWebCredentials` however it is only supported on iOS.
