### ISSUE TITLE
Does not build with ReactNative >= 40

### ISSUE THREAD

**Issue by huston007** [oblador/react-native-keychain#49]
They have changed import paths https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d

**Comment by AWDGroup** [comment]
+1 same problem!

**Comment by AWDGroup** [comment]
Thanks for fixing it, Which version should I use to have this fix?

**Comment by oblador** [comment]
Latest, 1.0.0
