### ISSUE TITLE
QUESTION: Is there a way to determine if credentials have been stored without triggering faceID?

### ISSUE THREAD

**Issue by austinGENEreeve** [oblador/react-native-keychain#519]
I have a login screen and I'd like to be able to determine if the user has saved credentials. If so I'll auto run faceID, retrieve their credentials and log the use in. 

The issue I'm having is using `const credentials = await Keychain.getGenericPassword(options);` to determine if the credentials exist. Is there a way to see if the credentials have been saved without using the biometrics? That way I don't auto run FaceID when the user hasn't set it up.

**Comment by husainkantawalaFS** [comment]
Save additional flag in storage after enabling, its a work around

**Comment by sgal** [comment]
@austinGENEreeve No API for this is currently exposed, but I think it is easy to add - at least for Android. Not sure about iOS though

**Comment by eightyfive** [comment]
Just for clarity @husainkantawalaFS means save some flag in [`AsyncStorage`](https://github.com/react-native-async-storage/async-storage).

```ts
const hasRegistered = (await AsyncStorage.getItem('hasRegistered')) || false;
```
