### ISSUE TITLE
Error with newest libraries

### ISSUE THREAD

**Issue by eksek** [oblador/react-native-keychain#52]
Creating a fresh project using "react-native init test" and then installing react-native-keychain and trying setGenericPassword (or any other method) will always give the following error:
undefined is not an object (evaluating '_reactNativeKeychain2.default.setGenericPasswrod')

I have another project on the same machine (initiated from native base boilerplate) which works fine. So I assume this has something to do with some versions but I have no idea what is different. I can supply any information needed.

**Comment by oblador** [comment]
The export method has changed to ES2017 with the release of 1.0.0. You should import it with `import * as Keychain from 'react-native-keychain';`.

**Comment by eksek** [comment]
Wow that was a fast answer and it worked. Thank you very much!

**Comment by Mjuk-Biltvatt** [comment]
I'm having the same issue right now and `import * as Keychain from 'react-native-keychain';` doesn't seem to work for me. I'm getting the same error `undefined is not an object (evaluating '_reactNativeKeychain2.default.setGenericPassword')`. Any ideas?
