### ISSUE TITLE
 Could not resolve all artifacts for configuration ':react-native-keychain:classpath'.

### ISSUE THREAD

**Issue by zhengyanGit** [oblador/react-native-keychain#523]
版本8.0.0 gradle-test-logger-plugin-2.0.0.pom这个依赖下载不下来

**Comment by oblador** [comment]
Please use English

**Comment by ashishAmz** [comment]
Hi @oblador, I am also getting this issue while generating APK 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':react-native-keychain:debugUnitTestRuntimeClasspath'.
   > Failed to transform bcprov-jdk15on-1.68.jar (org.bouncycastle:bcprov-jdk15on:1.68) to match attributes {artifactType=processed-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /Users/AshishL/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.68/46a080368d38b428d237a59458f9bc915222894d/bcprov-jdk15on-1.68.jar.
         > Failed to transform '/Users/AshishL/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.68/46a080368d38b428d237a59458f9bc915222894d/bcprov-jdk15on-1.68.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

**Comment by zhengyanGit** [comment]
方案版本降级 
a. 报错 ： Could not resolve all artifacts for configuration ':react-native-keychain:classpath'.
处理：版本降级 6.2.0
b. ios 添加依赖： cd ios &amp;&amp; pod install

**Comment by qasimgit** [comment]
having the same issue,

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':react-native-keychain:debugUnitTestRuntimeClasspath'.
   > Failed to transform bcprov-jdk15on-1.68.jar (org.bouncycastle:bcprov-jdk15on:1.68) to match attributes {artifactType=processed-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.68/46a080368d38b428d237a59458f9bc915222894d/bcprov-jdk15on-1.68.jar.

**Comment by mayconline** [comment]
> having the same issue, @oblador can you reopen this issue please.
> 
> * What went wrong:
>   Execution failed for task ':app:lintVitalRelease'.
> 
> > Could not resolve all artifacts for configuration ':react-native-keychain:debugUnitTestRuntimeClasspath'.
> > Failed to transform bcprov-jdk15on-1.68.jar (org.bouncycastle:bcprov-jdk15on:1.68) to match attributes {artifactType=processed-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
> > > Execution failed for JetifyTransform: gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.68/46a080368d38b428d237a59458f9bc915222894d/bcprov-jdk15on-1.68.jar.

Same issue, i'm run: 

```
cd android
./gradlew clean
./gradlew assembleRelease
```


return:

> Task :app:lintVitalRelease FAILED

FAILURE: Build failed with an exception.

```
* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':react-native-keychain:debugUnitTestRuntimeClasspath'.
   > Failed to transform bcprov-jdk15on-1.68.jar (org.bouncycastle:bcprov-jdk15on:1.68) to match attributes {artifactType=processed-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /home/user/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.68/46a080368d38b428d237a59458f9bc915222894d/bcprov-jdk15on-1.68.jar.
         > Failed to transform '/home/user/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.68/46a080368d38b428d237a59458f9bc915222894d/bcprov-jdk15on-1.68.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)
```

**Comment by mariouzae** [comment]
This is not a great solution, but I ended up adding this to the Jetify blacklist in the gradle.properties:

`android.jetifier.blacklist=bcprov-jdk15on`

**Comment by MarcosJBM** [comment]
> This is not a great solution, but I ended up adding this to the Jetify blacklist in the gradle.properties:
> 
> `android.jetifier.blacklist=bcprov-jdk15on`
<img width="1408" alt="Screenshot 2023-10-20 at 15 48 41" src="https://github.com/oblador/react-native-keychain/assets/67931411/dbfd6664-85b5-43a8-bc04-aeda58365a77">

Unfortunately, it didn't work for me, I still have the same error, it only happens when generating an APK, in debug no error happens.

"react-native": "0.66.4",
"react-native-keychain": "^8.1.2",
