### ISSUE TITLE
 Could not resolve all artifacts for configuration ':react-native-keychain:classpath'.

### ISSUE THREAD

**Issue by zhengyanGit** [oblador/react-native-keychain#524]
版本8.0.0 gradle-test-logger-plugin-2.0.0.pom这个依赖下载不下来，版本6.2.0 没这个问题

**Comment by oblador** [comment]
Duplicate of https://github.com/oblador/react-native-keychain/issues/523

**Comment by samiullah0243preesoft** [comment]
you just need to do npx jetify

**Comment by teogomes** [comment]
Try upgrading com.android.tools.build:gradle
