### ISSUE TITLE
[Android] How to share Keychain elements between multiple apps?

### ISSUE THREAD

**Issue by milkers** [oblador/react-native-keychain#53]
I am using this module to share login information across multiple, at least 4, applications. I have achieved this on iOS using this module. However the same code does not work on Android as I expected. I am using `Keychain.getInternetCredentials(server)` and `Keychain.setInternetCredentials(server, username, pass)` functions. Each app uses these operations with a common `server` string as a parameter. My problem is I set from app A and get from app B but I could not retrieve the data that I set from app A.

**Comment by oblador** [comment]
Access group option is now supported in [1.1.0](https://github.com/oblador/react-native-keychain/releases/tag/v1.1.0) which should solve this use case.

**Comment by milkers** [comment]
In my case there is no problem with iOS. I am happy with Keychain functionality. However on Android it is not as easy as on iOS. In the end on Android I come up with writing to an external file with encryption to share among other apps. Because shared preferences of Android do not solve my case. If I gain enough Android native knowledge I would be happy to create a PR but I am not expecting that soon. Thank you for this module anyways, cheers.

**Comment by MacKentoch** [comment]
It seems like coming android O will help: [autofill framework](https://developer.android.com/preview/features/autofill.html#optimizing_your_app_for_autofill)

**Comment by oblador** [comment]
Closing this for now, would love a PR for the android stuff but don't have this need myself currently.

**Comment by RWOverdijk** [comment]
Is there another issue that's tracking progress on this feature? I'm in need of this and would like to know if work for sharing credentials between several app has been done yet.

**Comment by gabrielmoncea** [comment]
👍

**Comment by 17Amir17** [comment]
Anyone working on this?
