### ISSUE TITLE
Macos getSupportedBiometryType() returns null 

### ISSUE THREAD

**Issue by dez64ru** [oblador/react-native-keychain#543]
Ive run app on air m1 (with fingerprint power button)
But ```Keychain.getSupportedBiometryType()``` always return null.
How i can prompt auth with Touch Id?

**Comment by dez64ru** [comment]
Just need to add Keychain Share into xcode project settings
I think its need to doc
For search: errSecMissingEntitlement, Internal error when a required entitlement isn't present

**Comment by alvesvin** [comment]
Thank you man, you are awesome!
