### ISSUE TITLE
Is it possible to use this library for reactjs web?

### ISSUE THREAD

**Issue by faso-dev** [oblador/react-native-keychain#546]
Hi!
First of all sorry for the outcome if it does not respect your rules.

I'm looking for a way to make my `localStorage` a bit more secure to store just some information(`token`, `role`) related to an authentication by `jwt` and I came across this library which unfortunately as the name indicates, is only for react native. 

My question is to know if it is not possible to use a part of this library to store my data ? Just setter and read.

Thanks a lot !

**Comment by oblador** [comment]
Nope, web is not supported and I don't really see a way it could be without storing these secrets in clear text.

**Comment by faso-dev** [comment]
> Nope, web is not supported and I don't really see a way it could be without storing these secrets in clear text.

Thank you for the feedback. My goal was to make the value stored in localStorage unreadable. If a user were to do a localStorage.getAll(), he wouldn't be able to see directly understandable values. And that's what I thought I understood with this library, which encrypts stored values.
