### ISSUE TITLE
Question - New version

### ISSUE THREAD

**Issue by mateosilguero** [oblador/react-native-keychain#548]
Hi ! Since this commit 6963bfd6c1e4e70b23c02f54e319523b62077aef, Are you considering publish a new version related with 0.68 ? This lib doesnt work for me when new arch is enabled.

**Comment by oblador** [comment]
8.1.0 has just been released, however AFAIK 8.0.0 should be compatible with new architecture.

**Comment by mateosilguero** [comment]
Thanks !

Yes, 8.0 does. Sorry, i was initilizating `packages.add(new KeychainPackage(new KeychainModuleBuilder().withoutWarmUp()));` on the old RNHost.
