### ISSUE TITLE
[Android] undefined is not an object (evaluating 'RNKeychainManager.getGenericPasswordForOptions')

### ISSUE THREAD

**Issue by pdoggi** [oblador/react-native-keychain#55]
React Native Noob here.

In Android only, `Keychain.getGenericPassword()` causes `undefined is not an object (evaluating 'RNKeychainManager.getGenericPasswordForOptions')` at this [location](https://github.com/oblador/react-native-keychain/blob/master/index.js#L125) .

iOS works fine. 

In the Android project, I checked manually that everything was linked properly. I am using the FBSDK and have added `new FBSDKPackage(mCallbackManager)` to `getPackages()` in `MainApplication.java`. `new KeychainPackage()` is added right after the FBSDK package. Prior to installing `react-native-keychain`, components from FBSDK displayed fine, but after installing and linking `react-native-keychain`, the components from FBSDK no longer render in Android (except for a red outline around the missing component). I don't know if it's related, but maybe it is.

Any help would be appreciated! Thanks.

Connie

**Comment by negator** [comment]
This seems to occur occasionally when the `react link` procedure fails to update the `MainApplication.java`, to register the `KeychainPackage()` React Package. If you manually update the `getPackages()` method, it work:

`myapp/android/app/src/main/java/com/.../MainApplication.java`
```
package com.myapp;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.oblador.keychain.KeychainPackage;  //Include the correct import

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new KeychainPackage()   //Specify the KeychainPackage
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```

**Comment by oblador** [comment]
It sounds like your native dependencies are not correctly linked for some reason. Did you happen to also upgrade react native or something?

**Comment by oblador** [comment]
Closing due to lack of feedback.

**Comment by jaxatto** [comment]
Having same issue/error message but with iOS! Any ideas?

**Comment by amit13091992** [comment]
Any luck with this issue???
