### ISSUE TITLE
Keychain.getGenericPassword Issue

### ISSUE THREAD

**Issue by chamaldesilva** [oblador/react-native-keychain#562]
Tried to set service value like this,

await Keychain.setGenericPassword(key, value, { service: key });

Ex: await Keychain.setGenericPassword('tokens', JSON.stringify({ token1, token2 }), { service: 'tokens' });

but Keychain.getGenericPassword() returns the "service" value with an empty string like this ""

"react-native-keychain": "6.2.0"
"react-native": "0.63.3"

What is the issue?

**Comment by irodeanu** [comment]
I have same issue only for iphone 14 pro
