### ISSUE TITLE
Are entries added to the Keychain synchronized to iCloud (and Android equivalent)?

### ISSUE THREAD

**Issue by bumpingChris** [oblador/react-native-keychain#568]
After using setInternetCredentials to add an entry into the Keychain, would the entry be synchronized to iCloud (and Android equivalent) to other devices?

Thanks for your help.

**Comment by jtvargas** [comment]
No

**Comment by bumpingChris** [comment]
@jtvargas Thanks for the prompt response. How can i make the credentials persist across devices?
Thanks

**Comment by jtvargas** [comment]
You can take a look on this Stackoverflow response about how to get the autofill and save the credentials in the iCloud Keychain: https://stackoverflow.com/questions/56524461/how-to-get-ios-12-autofill-to-ask-to-save-password-in-react-native-app

**Comment by DorianMazur** [comment]
iCloud sync was added in [9.1.0](https://github.com/oblador/react-native-keychain/releases/tag/v9.1.0)
