### ISSUE TITLE
Incompatible version of Kotlin

### ISSUE THREAD

**Issue by taatiq882** [oblador/react-native-keychain#575]
/Users/talhaatiq/.gradle/caches/transforms-3/a831348404dcf8b617273d52a45659cc/transformed/jetified-kotlin-stdlib-common-1.6.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. **The binary version of its metadata is 1.6.0, expected version is 1.4.0.**
Warning: com.oblador.keychain.KeychainModule.AccessControl: The typedef annotation should have @Retention(RetentionPolicy.SOURCE)
Warning: com.oblador.keychain.KeychainModule.KnownCiphers: The typedef annotation should have @Retention(RetentionPolicy.SOURCE)
Warning: com.oblador.keychain.KeychainModule.Rules: The typedef annotation should have @Retention(RetentionPolicy.SOURCE)

________________________________

    ext {
        kotlinVersion = "1.7.10"
        buildToolsVersion = "30.0.2"
        minSdkVersion = 24
        compileSdkVersion = 31
        targetSdkVersion = 30
        ndkVersion = "21.4.7075529"
    }

**Comment by AmitP1392** [comment]
any updates on this??

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=J0OSn7s9YiA&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=15

**Comment by DorianMazur** [comment]
This was fixed in 9.0.0 refactor.
