### ISSUE TITLE
React native keychain only working for iOS with TouchID,Pin,Password

### ISSUE THREAD

**Issue by paramjitzzzzz** [oblador/react-native-keychain#583]
Hi team,

React native keychain only working for iOS with TouchID,Pin,Password. For android only TochId is working no pin or password is there. Anyone please help me with a npm or any useful library that supports both android and iOS with at-least TouchID, faceID , Pin or password. 

# Any paid libraries are also welcome.
Thanks

**Comment by tomoakley** [comment]
Face ID definitely works in this package (been using it for 4 years). Did you follow step 3 in the installation instructions?

> If you want to support FaceID, add a NSFaceIDUsageDescription entry in your Info.plist.

if it's still not working share your code. We can't help much withot any code.

**Comment by clauderobi** [comment]
I think the OP was about Android, not iOS.
