### ISSUE TITLE
Use AES with block mode GCM

### ISSUE THREAD

**Issue by matteodanelli** [oblador/react-native-keychain#587]
Actually, the cipher created using AES is using block mode CBC.
According to [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html#cipher-modes) guidelines, it's better to use AES with block mode GCM, which is already available inside android.KeyProperties.
GCM can prevent CBC attacks like Chosen Plaintext Attack(CPA) and Chosen Ciphertext Attack(CCA)

Are there any known limitations to switch to this?

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=J0OSn7s9YiA&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=15

**Comment by Aure77** [comment]
This issue has been fixed in #681 
https://github.com/oblador/react-native-keychain/releases/tag/v9.2.0

**Comment by DorianMazur** [comment]
Fixed in 9.2.0
