### ISSUE TITLE
when I run my project, throw this error , how can solve this ?

### ISSUE THREAD

**Issue by vishuk570** [oblador/react-native-keychain#597]
buildToolsVersion = "31.0.0"
minSdkVersion = 21
compileSdkVersion = 31
 targetSdkVersion = 31
<>
Task :react-native-keychain:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
334 actionable tasks: 334 executed
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: F:\tc_SEED_Project\CSD-Seed-App\node_modules\@react-native-community\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: F:\tc_SEED_Project\CSD-Seed-App\node_modules\react-native-geolocation-service\android\src\main\java\com\agontuk\RNFusedLocation\LocationUtils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: F:\tc_SEED_Project\CSD-Seed-App\node_modules\@react-native-google-signin\google-signin\android\src\main\java\com\reactnativegooglesignin\RNGoogleSigninModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: F:\tc_SEED_Project\CSD-Seed-App\node_modules\@react-native-google-signin\google-signin\android\src\main\java\com\reactnativegooglesignin\RNGoogleSigninModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
F:\tc_SEED_Project\CSD-Seed-App\node_modules\react-native-keychain\android\src\main\java\com\oblador\keychain\cipherStorage\CipherStorageBase.java:528: error: lambda expressions are not supported in -source 7
    public static final EncryptStringHandler encrypt = (cipher, key, output) -> {
                                                                             ^
  (use -source 8 or higher to enable lambda expressions)
F:\tc_SEED_Project\CSD-Seed-App\node_modules\react-native-keychain\android\src\main\java\com\oblador\keychain\decryptionHandler\DecryptionResultHandlerInteractiveBiometric.java:111: error: method references are not supported in -source 7
      activity.runOnUiThread(this::startAuthentication);
                                   ^
  (use -source 8 or higher to enable method references)
F:\tc_SEED_Project\CSD-Seed-App\node_modules\react-native-keychain\android\src\main\java\com\oblador\keychain\decryptionHandler\DecryptionResultHandlerInteractiveBiometricManualRetry.java:78: error: method references are not supported in -source 7
      activity.runOnUiThread(this::startAuthentication);
                                   ^
  (use -source 8 or higher to enable method references)
F:\tc_SEED_Project\CSD-Seed-App\node_modules\react-native-keychain\android\src\main\java\com\oblador\keychain\KeychainModule.java:157: error: method references are not supported in -source 7
    final Thread warmingUp = new Thread(instance::internalWarmingBestCipher, "keychain-warming-up");
                                                  ^
  (use -source 8 or higher to enable method references)
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-keychain:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
<>

**Comment by varunkukade** [comment]
Keep check on https://github.com/oblador/react-native-keychain/pull/585
