### ISSUE TITLE
Attempt to invoke interface method 'java.lang.String com.oblador.keychain.cipherStorage.CipherStorage.getCipherStorageName()' on a null object reference

### ISSUE THREAD

**Issue by MAKARD** [oblador/react-native-keychain#602]
Version 8.1.1

Stacktrace:
`Error: Attempt to invoke interface method 'java.lang.String com.oblador.keychain.cipherStorage.CipherStorage.getCipherStorageName()' on a null object reference
    at Object.getGenericPasswordForOptions (index.android.bundle:58:1103)
    at O (index.android.bundle:748:3104)
    at Function.<anonymous> (index.android.bundle:747:1739)
    at Generator.next (<anonymous>)
    at n (index.android.bundle:8:70)
    at v (index.android.bundle:8:281)
    at u (index.android.bundle:100:157)
    at index.android.bundle:100:869
    at index.android.bundle:106:1663
    at k (index.android.bundle:106:498)`
    
Affected devices and versions
<img width="430" alt="image" src="https://github.com/oblador/react-native-keychain/assets/25794983/0a8311c6-fee6-49e2-ad89-fda8567caf2e">

Number of occurrences May 20-Jun 20 - 23.1k

Code sample:
```
import {
  getGenericPassword,
  ACCESS_CONTROL,
  ACCESSIBLE,
  SECURITY_RULES,
} from 'react-native-keychain';

const SERVICE_CREDENTIALS = 'com.myapp-keychain';

export class CredentialsManager {
  public static get = async () => {
    const options = {
      accessControl: ACCESS_CONTROL.BIOMETRY_ANY_OR_DEVICE_PASSCODE,
      accessible: ACCESSIBLE.ALWAYS,
    };

    const credentials = await getGenericPassword({
      ...options,
      service: SERVICE_CREDENTIALS,
      authenticationPrompt: {
        title: 'Confirm login to continue',
      },
      rules: SECURITY_RULES.NONE,
    });

    if (!credentials || !credentials.username || !credentials.password) {
      return false;
    }

    return {
      username: credentials.username,
      password: credentials.password,
    };
  };
}
```

**Comment by CodeAndyCode** [comment]
+

**Comment by AlixH** [comment]
up

**Comment by DorianMazur** [comment]
Hey @MAKARD,
Is this issue still occurring in the latest version?

**Comment by MAKARD** [comment]
@DorianMazur  We don't use this package anymore, so unfortunately can't answer your question
