### ISSUE TITLE
Android Hardware keystore

### ISSUE THREAD

**Issue by dhivya0413** [oblador/react-native-keychain#603]
What happens in android if hardware backed key store not supported ?  Can someone help me on understanding generic password get stored in terms of SECURITYLEVEL_HARDWARE and SECURITYLEVEL_SOFTWARE or Any? 

Please help on it.

**Comment by kuchbhihosaktahai** [comment]
https://www.youtube.com/watch?v=J0OSn7s9YiA&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=9
