### ISSUE TITLE
[Android] getSupportedBiometryType() always returns value even if the fingerprints are disabled.

### ISSUE THREAD

**Issue by rushilp2311** [oblador/react-native-keychain#611]
How do I check if the fingerprints are enrolled but disabled on the device?

The getSupportedBiometryType() always returns a value if the fingerprints are enrolled.

Any suggestion?

**Comment by dotsenko** [comment]
@rushilp2311 You disable biometry for the Lock screen, biometry keeps if you just disable fingerprint in the Lock screen settings
