### ISSUE TITLE
Warning when using SetGenericPassword with service

### ISSUE THREAD

**Issue by MartijnBooijAppronto** [oblador/react-native-keychain#618]
Hi,
when we use SetGenericPassword as follows, we get a warning message in our log.

```
export async function JS_SetGenericPassword(username, password, service) {
	await Keychain.setGenericPassword(username, password, service);
}

```
Warning message is:
`You passed a service string as an argument to one of the react-native-keychain functions. This way of passing service is deprecated and will be removed in a future major`

What should be future proof way?

**Comment by clauderobi** [comment]
Well, there is a further line in the warning message. It says this: Please update your code to use { service: "<What ever I used for username>" }

This is not clear.... Is the service == username?

 And where would this object go? In place of the secret argument?

And why wasn't the warning message sent on when using getPassphrase?

**Comment by JuliAnyday** [comment]
Hi, what was the solution you ended up going with?
