### ISSUE TITLE
Unrecognized platform name visionOS error

### ISSUE THREAD

**Issue by c100k** [oblador/react-native-keychain#624]
The [last update](https://github.com/oblador/react-native-keychain/compare/v8.1.3...v8.2.0) seems to have created breaking changes. When bumping from `8.1.3` to `8.2.0` and building, Xcode is not able to make it work.

![Screenshot 2024-03-01 at 16 54 51](https://github.com/oblador/react-native-keychain/assets/5722457/c3d51f02-7755-4d7f-821b-d866daf80194)

I'm getting the following errors:

- `Unrecognized platform name visionOS`
- `Use of undeclared identifier 'LABiometryTypeOpticID'`

**Config**

- Xcode `14.2`
- RN `0.73.5`

**Comment by uranashel44** [comment]
Same

**Comment by jayweb007** [comment]
same here

**Comment by c100k** [comment]
Please don't comment "Same", it doesn't bring anything to the issue. Add more information on your setup or simply upvote the original post.

**Comment by aslihanturkdonmez** [comment]
I was using `"react-native-keychain:^8.1.2" `and after pod installation I got this error:

> `Invalid `RNKeychain.podspec` file: undefined method `visionos' for #<Pod::Specification name="RNKeychain`

When I check my npm list I saw my react-native-keychain version is "8.2.0". Then I change to "react-native-keychain:~8.1.2" and pod install worked without any problem.

**Comment by uranashel44** [comment]
> I was using `"react-native-keychain:^8.1.2" `and after pod installation I got this error:
> 
> > `Invalid `RNKeychain.podspec`file: undefined method`visionos' for #<Pod::Specification name="RNKeychain`
> 
> When I check my npm list I saw my react-native-keychain version is "8.2.0". Then I change to "react-native-keychain:~8.1.2" and pod install worked without any problem.
> 
> Im using react-native: 72.4

Hi. I have had the same.
Please go to node_modules/react-native-keychain/RNKeychain.Podspec and comment the line which starts first/includes with "visionos", it will help your project runable before the maintainer can fix the issue.

**Comment by c100k** [comment]
Note that if you don't need the changes introduced in `8.2.0`, it's safer to downgrade and fix the dependency to `8.1.3` (not `^8.1.2`).

You don't know the side effects that you can introduce by commenting a line of code in a config file of a dependency.

**Comment by EmanuelMaciel** [comment]
Hello, I changed the Keychain version to 8.1.3 and was successful in executing the action and compiling the project.

Packages:
- Mac 12
- Node 20
- Keychain 8.1.3

**Comment by tomerh2001** [comment]
Any updates?

**Comment by thiagobrez** [comment]
PR with the fix is under review: https://github.com/oblador/react-native-keychain/pull/631
