### ISSUE TITLE
React Native 0.69.12: Could not find any matches for "com.facebook.react:react-android:+"

### ISSUE THREAD

**Issue by christophby** [oblador/react-native-keychain#666]
Only if I replace

```implementation "com.facebook.react:react-android:+"```

with

``` implementation "com.facebook.react:react-native:+```

in [node_modules/react-native-keychain/android/bulid.gradle](https://github.com/oblador/react-native-keychain/blob/master/android/build.gradle#L74) 

I can run an build the app.

Otherwise I'm getting the build error

> Could not find any matches for "com.facebook.react:react-android:+" as no versions of com.facebook.react:react-android are available. Required by: project :react-native-keychain

* "react-native-keychain": "9.0.0"
* "react-native": "0.69.12"

**Comment by christophby** [comment]
@DorianMazur thanks for solving. When do you plan to make a new release?

**Comment by DorianMazur** [comment]
@christophby This week
