### ISSUE TITLE
Get empty string while getting several values simultaneously on Android

### ISSUE THREAD

**Issue by amakarevich11** [oblador/react-native-keychain#679]
I'm experiencing a issue with getting several values simultaneously from keychain in my Expo React Native app. There is a problem that keychain returns empty string for one of the requests when we get values using ```getGenericPassword``` in ```Promise.all``` or executing multiple requests with our socket or REST service(they both use interceptors for every request to get multiple tokens from keychain). It reproduced only on Android almost in half of the cases.

Environment:
Expo SDK Version: 51.0.38
React Native Version: 0.74.5
react-native-keychain: 9.0.0
Platform: Android

**Comment by DorianMazur** [comment]
Fixed by #629
