### ISSUE TITLE
React Native 0.75 Warning Generated for Android

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [oblador/react-native-keychain#680]
Hi, Recently I have migrated app to React Native 0.75.3, with latest version of this package, I have observed few warning in debug mode as attached screenshots, features seems to be working fine.
react-native-keychain - 9.1.0

![Screenshot_1731326186](https://github.com/user-attachments/assets/6127fc64-5188-4483-ab29-d1f15c25330d)
![Screenshot_1731329696](https://github.com/user-attachments/assets/f2f14d79-ae7c-4e3e-8f5f-33e0114fdbf6)

Console log:

 (NOBRIDGE) WARN  Possible Unhandled Promise Rejection (id: 0):
com.oblador.keychain.exceptions.CryptoFailedException: Unknown error with alias: https://mobile-staging.intelex.dev/#mobile_development+automation@intelex.comUSER_INFO_KEY, error: javax.crypto.IllegalBlockSizeException
 (NOBRIDGE) WARN  Possible Unhandled Promise Rejection (id: 1):
com.oblador.keychain.exceptions.CryptoFailedException: Unknown error with alias: https://mobile-staging.intelex.dev/#mobile_development+automation@intelex.comSYSTEM_INFO_KEY, error: javax.crypto.IllegalBlockSizeException
 (NOBRIDGE) WARN  Possible Unhandled Promise Rejection (id: 2):
com.oblador.keychain.exceptions.CryptoFailedException: Unknown error with alias: https://mobile-staging.intelex.dev/#mobile_development+automation@intelex.comATLAS_TOKEN_KEY, error: IV has already been used. Reusing IV in encryption mode violates security best practices.

**Comment by DorianMazur** [comment]
Hi, can you provide example repository with this bug?

**Comment by ravindraguptacapgemini** [comment]
Hi @DorianMazur what is this AES_GCM_NO_AUTH ?

**Comment by DorianMazur** [comment]
https://oblador.github.io/react-native-keychain/docs/choosing-storage-type

**Comment by ravindraguptacapgemini** [comment]
@DorianMazur I guess the document is immature currently as it does explain much about opting for 'Choosing Storage Type'.
I want to understand if passing storage option is enough as STORAGE_TYPE.AES_GCM, or we need to pass other options (accessControl, accessible) as well. if so, please explain what does that mean for accessControl and accessible, do we need to authenticate the app with biometrics in that case?

**Comment by DorianMazur** [comment]
I don't understand your question. Storage option is enough, you don't need to pass anything else to make it work.
AES_GCM required biometrics just like RSA. AES_GCMP_NO_AUTH will work just like AES_CBC

**Comment by ravindraguptacapgemini** [comment]
currently I am not passing any storage option, should not this working fine with out storage?

**Comment by DorianMazur** [comment]
f you don't specify a storage option, the library will choose the best available storage method. If biometrics are enabled on the device, it will use AES_GCM, which requires biometric authentication. If biometrics are not available, it will use AES_GCM_NO_AUTH. For AES_GCM, you also need to pass an authenticationPrompt to the setGenericPassword function.

Now, I realized that the types for setGenericPassword need adjustment. I will release version 9.2.1 to address this, but it will be a change to the typings only.

**Comment by ravindraguptacapgemini** [comment]
this seems like a breaking change, if in case biometrics are enabled on the device, then we have to pass  authenticationPrompt

**Comment by DorianMazur** [comment]
That's not a breaking change; you can still use old cipher storages. Additionally, defaultPrompt will be used if authenticationPrompt is not provided.

**Comment by ravindraguptacapgemini** [comment]
yes, but we were not passing any storage option and no authenticationPrompt

**Comment by DorianMazur** [comment]
It will still work; the default authenticationPrompt will be used. You don't need to pass storage option for that.
