### ISSUE TITLE
Failed to get value from keychain on android devices with 35 API

### ISSUE THREAD

**Issue by amakarevich11** [oblador/react-native-keychain#688]
I am experiencing an issue with retrieving values from the keychain in my Expo React Native app. The issue started appearing after upgrading the project to Expo SDK 52.0.7 and React Native 0.76. It occurs only on new Android devices running API level 35 or higher. The issue does not throw any error; instead, the getGenericPassword call gets stuck in an infinite process, and the code after that line never executes. After downgrading to react-native-keychain version 9.0.0, the issue disappears.

Environment:
Expo SDK Version: 52.0.7
React Native Version: 0.76.2
react-native-keychain: 9.2.1
Platform: Android

**Comment by DorianMazur** [comment]
Hi @amakarevich11,

Could you please provide an example repository that reproduces this issue? This will help me investigate and resolve the problem :)

**Comment by amakarevich11** [comment]
Hi, executing of getGenericPassword is the only line of code that u need to reproduce the issue. U can take the default template of latest expo app and launch it with react-native-keychain@9.2.1 on the Android API 35.

**Comment by DorianMazur** [comment]
Hi @amakarevich11 
I can't reproduce the issue. I have added API levels 34 and 35 to the end-to-end tests, and they all passed successfully.
https://github.com/oblador/react-native-keychain/actions/runs/11942829765
<img width="735" alt="image" src="https://github.com/user-attachments/assets/0e42e89d-00f9-44f3-ba9a-81fdbc266e27">

**Comment by DorianMazur** [comment]
@amakarevich11 #691 should fix it. I will release 9.2.2 version today.

**Comment by amakarevich11** [comment]
ok, thank you for such quick help

**Comment by Bowlerr** [comment]
Hey,
I am also failing to get the keychain on **Android 15 ( Pixel 7a )** but it works as expected on Android 14 ( Oneplus 12 ).

`Wrapped error: The message could not be decrypted successfully.It has either been tampered with or the wrong resource is being decrypted.`

This is after upgrading from 8.2.0 -> 9.2.1 or 9.2.2.

I set the keychain on 8.2.0
update the app where the only change is updating the package.
try to get keychain, get the error.

@amakarevich11  any ideas what could be causing this?

**Comment by Bowlerr** [comment]
nvm it doesnt work as expected on the oneplus / android 14 same error
