### ISSUE TITLE
How to set Options ?

### ISSUE THREAD

**Issue by dburgmann** [oblador/react-native-keychain#69]
I am wondering how you can set options for keychain storage on iOS ?
for example I want to enforce the kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly attribute.

like:
Keychain.setInternetCredentials(server, user, pass, {kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly:true});

The native part requires a NSDictionary so i expected I need to submit a object. However this gives me a "callback is not a function" exception.
How am I expected to set Options?

**Comment by vonovak** [comment]
please see https://github.com/oblador/react-native-keychain/blob/d8ed753383abdde35879377fd3f9760f8f3eaaeb/index.js#L105 and https://github.com/oblador/react-native-keychain#keychainaccessible-enum
