### ISSUE TITLE
Suspicious code in getOptionsArgument

### ISSUE THREAD

**Issue by andriichernenko** [oblador/react-native-keychain#71]
`getOptionsArgument` in `index.js` seems suspicious:

```javascript
function getOptionsArgument(serviceOrOptions?: string | KeychainOptions) {
  if (Platform.OS !== 'ios') {
    return typeof serviceOrOptions === 'object' ? serviceOrOptions.service : serviceOrOptions;
  }

  return typeof serviceOrOptions === 'string' ? { service: serviceOrOptions } : serviceOrOptions;
}
```

On iOS it returns an options object creating it if a string is received, and vice versa on other platforms (returns a string, getting it from object if an object was received).

Is this intended?

**Comment by oblador** [comment]
Yes it's intended, because iOS takes multiple options whereas android does not.

**Comment by andriichernenko** [comment]
@oblador Is this method supposed to return different things on different platforms then? If this is the case, it would be great to have this documented.

**Comment by oblador** [comment]
Yup, iOS additional options part should be documented in plain text and not just flow/types. 

The native APIs have different signatures yes, so it's required.

Why do you call it with `null` and not just without arguments?

**Comment by andriichernenko** [comment]
> Why do you call it with null and not just without arguments?
Just a habit from Java/Swift :)
So it won't crash if `serviceOrOptions` is `undefined`, right?

**Comment by oblador** [comment]
Yep, think so!

**Comment by oblador** [comment]
But you don't have to pass any arguments at all

**Comment by andriichernenko** [comment]
Okay, thanks for help!
