### ISSUE TITLE
Shouldn't Conceal be set to use the native keystore?

### ISSUE THREAD

**Issue by Gerharddc** [oblador/react-native-keychain#73]
I see that Conceal can be used with a custom keychain implementation and that Android provides a native one https://developer.android.com/reference/java/security/KeyStore.html . I can't help but think that using Conceal to encrypt a value with a key stored in shared preferences provides no form of added security of all. The credentialism could themselves just be stored in shared preferences to provide the same level of security. A level of security that is quite useless on a stolen device.

**Comment by pcoltau** [comment]
We have just introduced the usage of the Android Keystore for API level +23. There is a release candidate that you can use: https://github.com/oblador/react-native-keychain/releases/tag/v2.0.0-rc

Please help us test it :-)

**Comment by Gerharddc** [comment]
Will do

**Comment by oblador** [comment]
@Gerharddc Did it work well for you? Haven't gotten too much feedback on the RC yet.

**Comment by Gerharddc** [comment]
@oblador sorry but I haven't got around to using it yet. I will let you know as soon as I do.

**Comment by oblador** [comment]
This is now released as stable in [2.0.0](https://github.com/oblador/react-native-keychain/releases/tag/v2.0.0), thus closing this issue.
