### ISSUE TITLE
React Native 0.47 removed createJSModules on Android

### ISSUE THREAD

**Issue by messense** [oblador/react-native-keychain#76]
https://github.com/facebook/react-native/releases/tag/v0.47.0

**Comment by alexgsummer** [comment]
Will get fixed with this PR: https://github.com/oblador/react-native-keychain/pull/80

**Comment by oblador** [comment]
Fixed in [1.2.1](https://github.com/oblador/react-native-keychain/releases/tag/v1.2.1)
