### ISSUE TITLE
React-native link don't detect this module

### ISSUE THREAD

**Issue by BenBenz** [oblador/react-native-keychain#77]
I've install react-native-keychain but when I type react-native link he links all of my native module expect react-native-keychain

**Comment by oblador** [comment]
This worked before, would you mind opening an issue at react-native core repo instead?

**Comment by alexgsummer** [comment]
I believe the issue exists in this project vs react-native core. I've been able to link other libs using React Native `0.47.0`.

**Comment by danielmartinprieto** [comment]
I just had this issue as well. `react-native link` _says_ it scans the folders for symlinks in `node_modules` and then does nothing.

**Comment by oblador** [comment]
Latest React Native works for a new project for me, so closing this issue for now.
