### ISSUE TITLE
[question] What does it mean when I get case errSecNotAvailable "No keychain is available. You may need to restart your computer."

### ISSUE THREAD

**Issue by amrdraz** [oblador/react-native-keychain#82]
I have an app that generally works fine in both production and development however one of the device it was installed on is giving this message, what does errSecNotAvailable mean

 "No keychain is available. You may need to restart your computer."

**Comment by jorgenbs** [comment]
same issue for certain ios devices

**Comment by ivanpagac** [comment]
have the same issue.

**Comment by vonovak** [comment]
hi! I'll close this since it is outdated. Also, as for questions, you may have better luck on stackoverflow.
