### ISSUE TITLE
RNKeychainManager is undefined

### ISSUE THREAD

**Issue by markewallace** [oblador/react-native-keychain#84]
Used these steps:
1. `yarn add react-native-keychain`
1. Manual installation for iOS (using `react-native link` didn't work, it corrupted the project file)
1. Run project from Xcode and it works fine

However when I run `react-native run-ios` I get this error `Unhandled JS Exception: Cannot read property 'getInternetCredentialsForServer' of undefined`

When I debug I can see that `RNKeychainManager` is undefined in `NativeModules`.

Anyone know what might be wrong?

**Comment by krystiansliwa** [comment]
Could you show here your iOS targets and Schemes?

**Comment by dmamills** [comment]
An import being undefined from `NativeModules` is a definite sign that the module has not been properly linked in your xcode project.

**Comment by danielfeelfine** [comment]
@markewallace you need to import in this way:

`import * as RNKeychainManager from 'react-native-keychain'`

instead of this:

`import RNKeychainManager from 'react-native-keychain'`
