### ISSUE TITLE
iOS Deployment Target 8.3

### ISSUE THREAD

**Issue by SoundBlaster** [oblador/react-native-keychain#86]
iTunesConnect does not accept application with minimum target 8.3 or 8.4 - only 8.2 or 9.0 are acceptable to upload build for now.
Can you downgrade deployment target to 8.2?
Relative post on Apple Forum - https://forums.developer.apple.com/thread/69614

**Comment by SoundBlaster** [comment]
Also connected with this issue #31

**Comment by vonovak** [comment]
closing as we moved deployment target to 9.0 https://github.com/oblador/react-native-keychain/pull/155
