### ISSUE TITLE
iOS keychain items are not erased when the app is uninstalled

### ISSUE THREAD

**Issue by andriichernenko** [oblador/react-native-keychain#87]
I am observing a behavior where keychain items are not deleted when the app is not uninstalled. While this might be desirable in some cases, it is definitely not for me.

There should be an opt-in way to reset the keychain on the first application start.

I suggest adding a method like `RNKeychainManager.resetKeychainIfFirstLaunch()`. This method will check a flag in `NSUserDefaults`, and if it is not set it will reset the keychain and set it. Developers opt in by calling this method at some point during the application start.

@oblador If you agree that this feature should be implemented, I can do it :)

**Comment by pcoltau** [comment]
Personally, I feel this should be handled in the app that uses this library, not the library it self.

**Comment by andriichernenko** [comment]
You're probably right.

**Comment by johnborges** [comment]
@AndrewJack Did you have an app level solution for this?

**Comment by AndrewJack** [comment]
@johnborges No? Did you mean to tag someone else?

**Comment by boarnoah** [comment]
I wonder if on iOS a potential solution is to clear the app specific keychain data on first run (assuming a reinstall). ex: https://stackoverflow.com/a/6203301
