### ISSUE TITLE
Error Domain=NSOSStatusErrorDomain Code=-909

### ISSUE THREAD

**Issue by Naoto-Ida** [oblador/react-native-keychain#89]
Hi we've been getting this error and haven't found any fixes for this.
We don't use any autofill methods, so I'm suspecting this lib might have something to do with it.
Any thoughts?

```
Error Domain=NSOSStatusErrorDomain Code=-909 "Autofill is not enabled in Safari settings" UserInfo={NSDescription=Autofill is not enabled in Safari settings}
```

**Comment by Naoto-Ida** [comment]
Ah ok, we didn't have a `catch()` for the following:
````
Keychain.requestSharedWebCredentials()
                .then(credentials => {
                 ...
                }).catch((e) => console.warn(e));
````

and our bug reporting tool was reporting this.

**Comment by cummings** [comment]
@Naoto-Ida How did you manage to solve this?
I the have the same error.

**Comment by Naoto-Ida** [comment]
@cummings This is not really an 'error' for us, so we just make sure we have a `catch()` and deal with them accordingly.
