### ISSUE TITLE
Any chance we can make the next release candidate for 2.0.0-rc?

### ISSUE THREAD

**Issue by chris-yoon90** [oblador/react-native-keychain#92]
Hi @oblador 

I'd like to update my app from using react-native 0.46 to >=0.47 but the current 2.0.0-rc doesn't include the fix to support >= 0.47. I've been using 2.0.0-rc on my app since it got released in July and it worked pretty well for me so far without any problems. Any chance we can release the next version of the release candidate that can support react-native >=0.47?

Thanks!

**Comment by jjessel** [comment]
Hey @chris-yoon90, release 1.2.1 shows compatibility with React Native 47.

**Comment by chris-yoon90** [comment]
@jjessel Ya, but I'm already using 2.0.0-rc. I prefer not to downgrade a major version since I'd like to have the security improvements made on Android on 2.0.0.

**Comment by oblador** [comment]
@chris-yoon90 I think it's time to release 2.0 as stable. Will fix compatibility too

**Comment by oblador** [comment]
It's here! [v2.0.0](https://github.com/oblador/react-native-keychain/releases/tag/v2.0.0)

**Comment by chris-yoon90** [comment]
yay! Thanks a lot!
