### ISSUE TITLE
Unexpected crypto version

### ISSUE THREAD

**Issue by raphkr** [oblador/react-native-keychain#94]
After updating my react-native version from 0.45 to 0.50.4 and downgrading react-native-keychain to 1.2.7 from 2.0.0-rc, I keep getting **RNKeychainManager: Unexpected crypto version** error msg when watching logs with the help of adb logcat

**Comment by oblador** [comment]
This is probably due to your keychain entry being migrated to KeyStore. Downgrading is not safe/supported!
