### ISSUE TITLE
Wrong response

### ISSUE THREAD

**Issue by SoundBlaster** [oblador/react-native-keychain#95]
Class `KeychainModule.java` contains line 112
``` credentials.putString("service", service);```
that returns service to the `getInternetCredentials` that declares returning  **`server`** - not `service`.
But in the `index.js` we have
```/**
 * Fetches login combination for `server`.
 * @param {string} server URL to server.
 * @param {object} options Keychain options, iOS only
 * @return {Promise} Resolves to `{ server, username, password }` when successful
 */
export function getInternetCredentials(
  server: string,
  options?: Options
): Promise {
  return RNKeychainManager.getInternetCredentialsForServer(server, options);
}
```
I don't have idea how to fix it only fix JSDoc content.

**Comment by vonovak** [comment]
closing as outdated, please open a new issue if the problem persists, ideally with a repro.
