### ISSUE TITLE
keychain.KeychainModule.setGenericPasswordForOptions

### ISSUE THREAD

**Issue by mariomarquess** [oblador/react-native-keychain#96]
I have been looking into some issues related to mine, but i can't find the right answer, it works when i use the debug version but when i try to use the release i got a problem when i use Keychain.setGenericPassword , i'm quite sure the problem is when login is valid i try to store the data:

```
if ( responseData.success )
{
    Keychain.setGenericPassword(this.state.username, this.state.password);
    GLOBAL.API_KEY = responseData.api_key;
    ( responseData.setupAccount ? Actions.conta() : Actions.home() );
}
```
I did the **adb logcat** command to see the exceptions and i got this:

> W/dalvikvm( 2935): Pending exception is: I/dalvikvm( 2935): java.lang.NoSuchFieldError: **no field with name='mCtxPtr' signature='J'** in class Lcom/facebook/crypto/cipher/NativeGCMCipher; I/dalvikvm( 2935): at java.lang.Runtime.nativeLoad(Native Method) I/dalvikvm( 2935): at java.lang.Runtime.loadLibrary(Runtime.java:368) I/dalvikvm( 2935): at java.lang.System.loadLibrary(System.java:535) I/dalvikvm( 2935):
> at com.facebook.crypto.util.SystemNativeCryptoLibrary.loadLibraries(SystemNativeCryptoLibrary.java:50) I/dalvikvm( 2935): at com.facebook.crypto.util.SystemNativeCryptoLibrary.ensureCryptoLoaded(SystemNativeCryptoLibrary.java:39) I/dalvikvm( 2935): at com.facebook.crypto.Crypto.isAvailable(Crypto.java:54) I/dalvikvm( 2935): **at com.oblador.keychain.KeychainModule.setGenericPasswordForOptions(KeychainModule.java:48)** I/dalvikvm( 2935): at java.lang.reflect.Method.invokeNative(Native Method) I/dalvikvm( 2935): at java.lang.reflect.Method.invoke(Method.java:511) I/dalvikvm( 2935): at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363) I/dalvikvm( 2935): at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:166) I/dalvikvm( 2935): at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) I/dalvikvm( 2935): at android.os.Handler.handleCallback(Handler.java:615) I/dalvikvm( 2935): at android.os.Handler.dispatchMessage(Handler.java:92)

**Comment by malonguwa** [comment]
@mariomarquess 
Keychain.setGenericPassword, is actually return a Promise, and you need to do something your own code in the "then".
Such as in the example,
      Keychain.setGenericPassword(username, password).then(function() {
          console.log('Credentials saved successfully!');
      });

You can give it a try~

**Comment by mariomarquess** [comment]
Hello,

Thank you for your tip, i did it in the code:

[image: Imagem intercalada 1]

Still the app is closing: "MyApp has stopped"

2018-01-04 7:56 GMT+00:00 malonguwa <notifications@github.com>:

**Comment by malonguwa** [comment]
@mariomarquess When you do the release build, have you added this
```
-keep class com.facebook.crypto.** {
   *;
}
```
 in your proguard-rules.pro file?
Please refer to https://github.com/oblador/react-native-keychain/blob/master/README.md#proguard-rules

![react-native-keychain](https://user-images.githubusercontent.com/2183780/34597960-fed599b4-f224-11e7-8513-94c3c0ede36f.jpeg)

**Comment by mariomarquess** [comment]
Yes, you are right, that was the problem, u saved me.

Thank you for your help, and i wish you a happy new year.

Best Regards,
Mário

2018-01-05 6:32 GMT+00:00 malonguwa <notifications@github.com>:
