### ISSUE TITLE
Operation couldn’t be completed. (com.apple.SafariServices.Authentication error 1.)

### ISSUE THREAD

**Issue by alb445** [oblador/react-native-keychain#99]
I want to share the same `Keychain` between multiple apps. For that I was planning to use `setSharedWebCredentials` and `requestSharedWebCredentials`. However I am getting an error when I try to set the credentials: 

`Error: Error Domain=NSOSStatusErrorDomain Code=-909 "Autofill is not enabled in Safari settings" UserInfo={NSDescription=Autofill is not enabled in Safari settings`

this is my code

```
Keychain
        .setSharedWebCredentials('server', 'username', 'password')
        .then(function() {
          console.log('Shared web credentials saved successfully!');
        }).catch(err => {
          console.error(err)
        });
```

I am running the app on iOS 11.1.2. Do you know how to solve the problem or is there any other method to share the keychain? `setGenericPassword` works to save a token but the keychain is not shared between the apps.

 Keychain sharing capability is already enabled and both apps use the same keychain group.

**Comment by oblador** [comment]
You can use the `accessGroup` option on iOS for this functionality.

**Comment by vonovak** [comment]
closing as outdated, please open a new issue if the problem persists, ideally with a repro.
